### ISSUE TITLE
PhoneCodeExpiredError not handled gracefully

### ISSUE THREAD

**Issue by vranki** [mautrix/telegram#326]
I tried logging in to telegram via the web page. After filling the registration form it just displayed Internal server error.

Stack trace reveals it's about PhoneCodeExpiredError:
```
May 29 22:07:36 matrix python[3598]: [2019-05-29 22:07:36,880] [ERROR@mau.web.public] Error requesting phone code
May 29 22:07:36 matrix python[3598]: Traceback (most recent call last):
May 29 22:07:36 matrix python[3598]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/web/common/auth_api.py", line 76, in post_login_phone
May 29 22:07:36 matrix python[3598]:     await user.client.sign_in(phone or "+123")
May 29 22:07:36 matrix python[3598]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/client/auth.py", line 264, in sign_in
May 29 22:07:36 matrix python[3598]:     return await self.send_code_request(phone)
May 29 22:07:36 matrix python[3598]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/client/auth.py", line 399, in send_code_request
May 29 22:07:36 matrix python[3598]:     functions.auth.ResendCodeRequest(phone, phone_hash))
May 29 22:07:36 matrix python[3598]:   File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/client/users.py", line 59, in __call__
May 29 22:07:36 matrix python[3598]:     result = await future
May 29 22:07:36 matrix python[3598]: telethon.errors.rpcerrorlist.PhoneCodeExpiredError: The confirmation code has expired (caused by ResendCodeRequest)
May 29 22:07:36 matrix python[3598]: [2019-05-29 22:07:36,883] [INFO@aiohttp.access] 127.0.0.1 [29/May/2019:19:07:36 +0000] "POST /telegrampublic/login?token=3b7859601cfdcxxxxxxxxxxxxxxxxxxxxxxxxxxxx289e966ea5:eyJteGlkIjogIkBjb3M0MjptYXRyaXgub3JnIxxxxxxxxxxxxxxxxxxxxxxx2dpbiIsICJleHBpcnkiOiAxNTU5MTU3NTY4fQ== HTTP/1.0" 500 2780 "https://matrix.hacklab.fi/telegrampublic/login?token=3b7859601cfdca1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxeffba6a2117ed289e966ea5:eyJteGlkIjogIkBjb3M0MjptYXRyaXgub3JnIiwgImxxxxxxxxxxxxxxxxxxxxxxxbiIsICJleHBpcnkiOiAxNTU5MTU3NTY4fQ==" "Mozilla/5.0 (Android 7.1.1; Tablet; rv:67.0) Gecko/67.0 Firefox/67.0"
```

The error should be handled gracefully and user should get proper error message and instructions on how to proceed.

**Comment by olmari** [comment]
Mautrix-telegram version at the time was https://github.com/tulir/mautrix-telegram/commit/1693b643a7e25589365f2baecf78e02d10d44559 FYI
