### ISSUE TITLE
Bridge stuck disconnected, had to restart

### ISSUE THREAD

**Issue by WGH-** [mautrix/telegram#386]
Today I checked the logs and noticed the following error during attempt to send a message:

```
[2019-11-24 16:58:08,439] [DEBUG@mau.mx] Received event: {'age': 130, 'content': {'body': '<REDACTED>', 'msgtype': 'm.text'}, 'event_id': '<REDACTED>', 'origin_server_ts': 1574614688290, 'room_id': '<REDACTED>', 'sender': '@WGH:torlan.ru', 'type': 'm.room.message', 'unsigned': {'age': 130}, 'user_id': '@WGH:torlan.ru'}
[2019-11-24 16:58:08,440] [DEBUG@mau.user] ensure_started(@WGH:torlan.ru, even_if_no_session=False)
[2019-11-24 16:58:08,444] [DEBUG@mau.mx] Received Matrix event "{'body': '<REDACTED>', 'msgtype': 'm.text'}" from <mautrix_telegram.user.User object at 0x7f4ea0b4d6a0> in <REDACTED>
[2019-11-24 16:58:08,451] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_appservice/appservice.py", line 173, in try_handle
    await handler_func(event)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 470, in handle_event
    await self.handle_message(room_id, sender, content, event_id)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/matrix.py", line 260, in handle_message
    await portal.handle_matrix_message(sender, message, event_id)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 1131, in handle_matrix_message
    await self._handle_matrix_text(sender_id, event_id, space, client, message, reply_to)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/mautrix_telegram/portal.py", line 1008, in _handle_matrix_text
    link_preview=lp)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/client/messages.py", line 715, in send_message
    result = await self(request)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/client/users.py", line 43, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "/opt/mautrix-telegram/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 159, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
[2019-11-24 16:58:08,454] [INFO@aiohttp.access] 127.0.0.1 [24/Nov/2019:16:58:08 +0000] "PUT /transactions/7846?access_token=<REDACTED> HTTP/1.1" 200 158 "-" "Synapse/1.1.0"
```

No error was shown to the user, so the only way to notice that was to check the logs. After restarting the bridge, the condition was fixed, and I got a bunch of Telegram messages, along with lots of weird redaction events attributed to different users, having assorted timestamps (up to couple of months ago).

```
aiohttp==3.5.4
alembic==1.0.7
async-generator==1.10
async-timeout==3.0.1
attrs==18.2.0
certifi==2019.3.9
chardet==3.0.4
commonmark==0.8.1
cryptg==0.1.0.7
decorator==4.3.2
future==0.17.1
future-fstrings==0.4.5
idna==2.8
idna-ssl==1.1.0
imageio==2.5.0
imageio-ffmpeg==0.2.0
lxml==4.3.1
Mako==1.0.7
MarkupSafe==1.1.0
mautrix-appservice==0.3.11
mautrix-telegram==0.6.0
moviepy==1.0.0
multidict==4.5.2
numpy==1.16.1
Pillow==5.4.1
proglog==0.1.9
prometheus-client==0.7.1
pyaes==1.6.1
pyasn1==0.4.5
python-dateutil==2.8.0
python-editor==1.0.4
python-magic==0.4.15
requests==2.21.0
rsa==4.0
ruamel.yaml==0.15.87
six==1.12.0
SQLAlchemy==1.2.17
Telethon==1.9.0
telethon-session-sqlalchemy==0.2.14
tqdm==4.31.1
typing-extensions==3.7.2
urllib3==1.24.1
yarl==1.3.0
```

**Comment by WGH-** [comment]
These messages sent on the Matrix side were never retransmitted to Telegram after restarting.

**Comment by WGH-** [comment]
Some messages from Telegram were lost as well.

**Comment by turt2live** [comment]
This appears to be what's happening (sometimes) to t2bot.io's bridge. Modern stack trace:

```
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]: [2023-07-14 20:55:04,422] [#033[31;1mERROR#033[0m@#033[32mmau.portal#033[0m.#033[33m1218594662#033[0m] Failed to bridge $event_id_redacted
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]: Traceback (most recent call last):
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2166, in handle_matrix_message
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     await self._handle_matrix_message(sender, content, event_id)
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2298, in _handle_matrix_message
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     await self._handle_matrix_text(
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 1805, in _handle_matrix_text
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     response = await client.send_message(
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/telethon/client/messages.py", line 901, in send_message
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     result = await self(request)
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     return await self._call(self._sender, request, ordered=ordered)
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/telethon/client/users.py", line 67, in _call
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     future = sender.send(request, ordered=ordered)
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:   File "/home/telegram/tgenv/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 177, in send
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]:     raise ConnectionError('Cannot send requests while disconnected')
Jul 14 20:55:04 integrations-10-do-fra1-t2host-io python[3750653]: ConnectionError: Cannot send requests while disconnected
```
