### ISSUE TITLE
deleting an edited messages fails

### ISSUE THREAD

**Issue by Bubu** [mautrix/telegram#429]
Tested in saved messages and a direct chat with double puppeting.

Send a message, edit that message, delete the message (all in telegram), the matrix side stays at the last edit, the log shows the following error:

```
[2020-02-19 13:17:27,742] [ERROR@mau.user.@bubu:bubu1.eu] Failed to handle Telegram update UpdateDeleteMessages(messages=[181483], pts=377651, pts_count=1)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 534, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 194, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 243, in _update
    await self.delete_message(update)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 390, in delete_message
    message.delete()
  File "/usr/lib/python3.8/site-packages/mautrix/util/db/base.py", line 186, in delete
    conn.execute(self.t.delete().where(self._edit_identity))
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2064, in __exit__
    self.transaction.commit()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1727, in commit
    self._do_commit()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1758, in _do_commit
    self.connection._commit_impl()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 757, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 534, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-02-19 13:17:27,750] [DEBUG@telethon.39080058.network.mtprotosender] Handling update UpdateShort
[2020-02-19 13:17:27,751] [DEBUG@telethon.39080058.network.mtprotosender] Receiving items from the network...
[2020-02-19 13:17:27,752] [DEBUG@telethon.39080058.network.mtprotosender] Handling update UpdateShort
[2020-02-19 13:17:27,752] [DEBUG@telethon.39080058.network.mtprotosender] Receiving items from the network...
[2020-02-19 13:17:27,753] [DEBUG@telethon.39080058.network.mtprotosender] Handling update UpdateShort
[2020-02-19 13:17:27,753] [DEBUG@telethon.39080058.network.mtprotosender] Receiving items from the network...
[2020-02-19 13:17:27,754] [DEBUG@telethon.39080058.network.mtprotosender] Handling update UpdateShort
[2020-02-19 13:17:27,754] [DEBUG@telethon.39080058.network.mtprotosender] Receiving items from the network...
[2020-02-19 13:17:32,959] [ERROR@mau.puppet.39080058] Fatal error syncing @bubu:bubu1.eu
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 280, in _try_sync
    await self._sync()
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 300, in _sync
    self.next_batch = sync_resp.get("next_batch", None)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 130, in next_batch
    self.db_instance.edit(next_batch=self._next_batch)
  File "/usr/lib/python3.8/site-packages/mautrix/util/db/base.py", line 157, in edit
    conn.execute(self.t.update()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE puppet SET next_batch=? WHERE puppet.id = ?]
[parameters: ('s1452556_35758109_598_1620902_37440_144_11100_244855_10', 39080058)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by tulir** [comment]
Works fine for me. "sqlite3.OperationalError: database is locked" sounds like it's just a side effect of some completely different problem

**Comment by pidongqianqian** [comment]
@Bubu i also saw this, can you tell me how you dealt with it？thankyou
