### ISSUE TITLE
[ERROR@mau.mx] Error handling manually received Matrix event

### ISSUE THREAD

**Issue by olmari** [mautrix/telegram#473]
I see occasional errors on telegram bridge logs, bridge ver https://github.com/tulir/mautrix-telegram/commit/fb1ab220ffd7f72c0d4e67e8947b0fcbbaa60d72

```
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,846] [DEBUG@telethon.72343648.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,846] [DEBUG@telethon.72343648.network.mtprotosender] Encrypted messages put in a queue to be sent
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,846] [DEBUG@telethon.72343648.network.mtprotosender] Waiting for messages to send...
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,846] [DEBUG@telethon.72343648.extensions.messagepacker] Assigned msg_id = 6831958550754342924 to MsgsAck (7fa0642d70f0)
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,846] [DEBUG@telethon.72343648.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,847] [ERROR@mau.mx] Error handling manually received Matrix event
touko 28 21:08:26 morpheus python[1602]: Traceback (most recent call last):
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 299, in try_handle_sync_event
touko 28 21:08:26 morpheus python[1602]:     await self.handle_ephemeral_event(evt)
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/matrix.py", line 406, in handle_ephemeral_event
touko 28 21:08:26 morpheus python[1602]:     await self.handle_read_receipts(evt.room_id, self.parse_read_receipts(evt.content))
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/matrix.py", line 362, in handle_read_receipts
touko 28 21:08:26 morpheus python[1602]:     await portal.mark_read(user, event_id)
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/mautrix_telegram/portal/matrix.py", line 118, in mark_read
touko 28 21:08:26 morpheus python[1602]:     clear_mentions=True)
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/telethon/client/messages.py", line 1198, in send_read_acknowledge
touko 28 21:08:26 morpheus python[1602]:     entity = await self.get_input_entity(entity)
touko 28 21:08:26 morpheus python[1602]:   File "/opt/telegrambot/lib/python3.7/site-packages/telethon/client/users.py", line 437, in get_input_entity
touko 28 21:08:26 morpheus python[1602]:     .format(peer)
touko 28 21:08:26 morpheus python[1602]: ValueError: Could not find the input entity for <telethon.tl.types.PeerChannel object at 0x7fa0641f14a8>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,847] [DEBUG@telethon.72343648.network.mtprotosender] Encrypted messages put in a queue to be sent
touko 28 21:08:26 morpheus python[1602]: [2020-05-28 21:08:26,847] [DEBUG@telethon.72343648.network.mtprotosender] Waiting for messages to send...
touko 28 21:08:27 morpheus python[1602]: [2020-05-28 21:08:27,715] [DEBUG@telethon.169105389.network.mtprotosender] Handling update UpdateShort
```

**Comment by elmehalawi** [comment]
Can I ask how you got these logs? When I run `docker logs <container id>`, I get this error:

    Error response from daemon: configured logging driver does not support reading
