### ISSUE TITLE
Restarting postgres stops read-receipts from working (until bridge is restarted)

### ISSUE THREAD

**Issue by Bubu** [mautrix/telegram#496]
When restarting postgres the bridge stops sending read-receipts until it's restarted itself. As the bridge itself is still working this failure mode is quite hard to detect.

Log:

```
Jul 07 17:03:56 bubu mautrix-telegram[117858]: [2020-07-07 17:03:56,884] [ERROR@mau.puppet.39080058] Fatal error syncing @bubu:bubu1.eu
Jul 07 17:03:56 bubu mautrix-telegram[117858]: Traceback (most recent call last):
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     self.dialect.do_execute(
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     cursor.execute(statement, parameters)
Jul 07 17:03:56 bubu mautrix-telegram[117858]: psycopg2.errors.AdminShutdown: terminating connection due to administrator command
Jul 07 17:03:56 bubu mautrix-telegram[117858]: server closed the connection unexpectedly
Jul 07 17:03:56 bubu mautrix-telegram[117858]:         This probably means the server terminated abnormally
Jul 07 17:03:56 bubu mautrix-telegram[117858]:         before or while processing the request.
Jul 07 17:03:56 bubu mautrix-telegram[117858]: The above exception was the direct cause of the following exception:
Jul 07 17:03:56 bubu mautrix-telegram[117858]: Traceback (most recent call last):
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 283, in _try_sync
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     await self._sync()
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 303, in _sync
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     self.next_batch = sync_resp.get("next_batch", None)
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/puppet.py", line 130, in next_batch
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     self.db_instance.edit(next_batch=self._next_batch)
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/util/db/base.py", line 157, in edit
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     conn.execute(self.t.update()
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     return meth(self, multiparams, params)
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     return connection._execute_clauseelement(self, multiparams, params)
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     ret = self._execute_context(
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     self._handle_dbapi_exception(
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     util.raise_(
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     raise exception
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     self.dialect.do_execute(
Jul 07 17:03:56 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Jul 07 17:03:56 bubu mautrix-telegram[117858]:     cursor.execute(statement, parameters)
Jul 07 17:03:56 bubu mautrix-telegram[117858]: sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
Jul 07 17:03:56 bubu mautrix-telegram[117858]: server closed the connection unexpectedly
Jul 07 17:03:56 bubu mautrix-telegram[117858]:         This probably means the server terminated abnormally
Jul 07 17:03:56 bubu mautrix-telegram[117858]:         before or while processing the request.
Jul 07 17:03:56 bubu mautrix-telegram[117858]: [SQL: UPDATE puppet SET next_batch=%(next_batch)s WHERE puppet.id = %(id_1)s]
Jul 07 17:03:56 bubu mautrix-telegram[117858]: [parameters: {'next_batch': 's1824573_48306087_4137_2140804_69976_207_14857_1035301_13', 'id_1': 39080058}]
Jul 07 17:03:56 bubu mautrix-telegram[117858]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Jul 07 17:22:35 bubu mautrix-telegram[117858]: [2020-07-07 17:22:35,744] [INFO@aiohttp.access] 127.0.0.1 [07/Jul/2020:15:22:35 +0000] "PUT /transactions/138234?access_token=ncf2b5b23rb4fjqp2o2gf0phq>
Jul 07 17:22:50 bubu mautrix-telegram[117858]: [2020-07-07 17:22:50,778] [INFO@telethon.92404833.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
Jul 07 17:23:01 bubu mautrix-telegram[117858]: [2020-07-07 17:22:59,659] [ERROR@mau.user.@plumbumstift:bubu1.eu] Failed to handle Telegram update UpdateNewMessage(message=Message(id=314048, to_id=Pe>
Jul 07 17:23:01 bubu mautrix-telegram[117858]: Traceback (most recent call last):
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 195, in _update_catch
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     await self._update(update)
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 242, in _update
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     await self.update_message(update)
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 440, in update_message
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     return await portal.handle_telegram_message(self, sender, update)
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in handle_telegram_message
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     event_id = await {
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 197, in handle_telegram_document
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     file = await util.transfer_file_to_matrix(source.client, intent, document, thumb_loc,
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 182, in transfer_file_to_matrix
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     return await _unlocked_transfer_file_to_matrix(client, intent, location_id, location,
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/util/file_transfer.py", line 238, in _unlocked_transfer_file_to_matrix
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     content_uri = await intent.upload_media(file, upload_mime_type)
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 75, in wrapper
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     return await __method(*args, **kwargs)
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/client/api/modules/media_repository.py", line 57, in upload_media
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     resp = await self.api.request(Method.POST, MediaPath.upload, content=data,
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     return await self._send(method, endpoint, content, query_params, headers or {})
Jul 07 17:23:01 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
Jul 07 17:23:01 bubu mautrix-telegram[117858]:     raise make_request_error(http_status=response.status,
Jul 07 17:23:01 bubu mautrix-telegram[117858]: mautrix.errors.request.MUnknown: Internal server error
Jul 07 17:23:57 bubu mautrix-telegram[117858]: [2020-07-07 17:23:57,315] [ERROR@mau.user.@plumbumstift:bubu1.eu] Failed to handle Telegram update UpdateShortChatMessage(id=314049, from_id=76360682, >
Jul 07 17:23:57 bubu mautrix-telegram[117858]: Traceback (most recent call last):
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     self.dialect.do_execute(
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     cursor.execute(statement, parameters)
Jul 07 17:23:57 bubu mautrix-telegram[117858]: psycopg2.errors.AdminShutdown: terminating connection due to administrator command
Jul 07 17:23:57 bubu mautrix-telegram[117858]: server closed the connection unexpectedly
Jul 07 17:23:57 bubu mautrix-telegram[117858]:         This probably means the server terminated abnormally
Jul 07 17:23:57 bubu mautrix-telegram[117858]:         before or while processing the request.
Jul 07 17:23:57 bubu mautrix-telegram[117858]: The above exception was the direct cause of the following exception:
Jul 07 17:23:57 bubu mautrix-telegram[117858]: Traceback (most recent call last):
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 195, in _update_catch
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     await self._update(update)
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 242, in _update
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     await self.update_message(update)
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/abstract_user.py", line 440, in update_message
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     return await portal.handle_telegram_message(self, sender, update)
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 530, in handle_telegram_message
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     DBMessage(tgid=TelegramID(evt.id), mx_room=self.mxid, mxid=event_id,
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/mautrix/util/db/base.py", line 197, in insert
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     conn.execute(self.t.insert().values(**self._insert_values))
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     return meth(self, multiparams, params)
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     return connection._execute_clauseelement(self, multiparams, params)
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     ret = self._execute_context(
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     self._handle_dbapi_exception(
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     util.raise_(
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     raise exception
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     self.dialect.do_execute(
Jul 07 17:23:57 bubu mautrix-telegram[117858]:   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
Jul 07 17:23:57 bubu mautrix-telegram[117858]:     cursor.execute(statement, parameters)
Jul 07 17:23:57 bubu mautrix-telegram[117858]: sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
Jul 07 17:23:57 bubu mautrix-telegram[117858]: server closed the connection unexpectedly
Jul 07 17:23:57 bubu mautrix-telegram[117858]:         This probably means the server terminated abnormally
Jul 07 17:23:57 bubu mautrix-telegram[117858]:         before or while processing the request.
Jul 07 17:23:57 bubu mautrix-telegram[117858]: [SQL: INSERT INTO message (mxid, mx_room, tgid, tg_space, edit_index) VALUES (%(mxid)s, %(mx_room)s, %(tgid)s, %(tg_space)s, %(edit_index)s)]
Jul 07 17:23:57 bubu mautrix-telegram[117858]: [parameters: {'mxid': '$M3tSRVc4ztyDqF8lmVeBLXle0KYCTqhuH87RkKy6Fhg', 'mx_room': '!wgOqrBPOzovDnWXxpm:bubu1.eu', 'tgid': 314049, 'tg_space': 92404833, >
Jul 07 17:23:57 bubu mautrix-telegram[117858]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by tulir** [comment]
Probably fixed
