### ISSUE TITLE
Loads of failed takeouts after login and initial sync

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#537]
When my bot try to do initial backfill it spams me with failed takeouts for very many chats.
Example of 2:
```
mautrix-telegram_1           | [2020-11-11 02:00:45,410] [ERROR@mau.portal.[MY_ID]<->[ID_1]] Failed to backfill new portal                                                                                                             
mautrix-telegram_1           | Traceback (most recent call last):                                                                                                                                                                           
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 421, in _create_matrix_room                                                                                              
mautrix-telegram_1           |     await self.backfill(user, is_initial=True)                                                                                                                                                               
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill                                                                                                         
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)                                                                                                                                          
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill                                                                                                 
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)                                                                                                                                                              
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill                                                                                                        
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:                                                                                                                                           
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__                                                                                                                 
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "                                                                                                                                           
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.                                                                                          
mautrix-telegram_1           | [2020-11-11 02:00:45,597] [ERROR@mau.portal.[MY_ID]<->[ID_2]] Failed to backfill new portal                                                                                                             
mautrix-telegram_1           | Traceback (most recent call last):                                                                                                                                                                           
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/metadata.py", line 421, in _create_matrix_room                                                                                              
mautrix-telegram_1           |     await self.backfill(user, is_initial=True)                                                                                                                                                               
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill                                                                                                         
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)                                                                                                                                          
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill                                                                                                 
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)                                                                                                                                                              
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill                                                                                                        
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.
```
Telegram asked me for takeout permissions once, I allowed it and then started spamming like that.
In effect only few of my chats got backfilled.

**Comment by JuniorJPDJ** [comment]
I've similar error when I run `!tg backfill` on any chat.
```
mautrix-telegram_1           | [2020-11-11 02:47:22,399] [ERROR@mau.commands] Unhandled error while handling command backfill  from @juniorjpdj:juniorjpdj.pl (ref: 1605059643)
mautrix-telegram_1           | Traceback (most recent call last):
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 404, in handle
mautrix-telegram_1           |     await self._run_handler(handler, evt)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
mautrix-telegram_1           |     return await handler(evt)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 289, in __call__
mautrix-telegram_1           |     return await self._handler(evt)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/telegram/misc.py", line 353, in backfill
mautrix-telegram_1           |     await portal.backfill(evt.sender, limit=limit)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.
```

**Comment by JuniorJPDJ** [comment]
Is there something I could provide to make this bugfix faster? I'm having my bridge disabled for over 2 weeks now, as I don't want too loose messages ;/

**Comment by JuniorJPDJ** [comment]
It seems to work after telethoon update, I'll close atm.

**Comment by JuniorJPDJ** [comment]
```
mautrix-telegram_1           | [2020-12-09 08:08:25,305] [ERROR@mau.user.@juniorjpdj:juniorjpdj.pl] Error while backfilling 388773942<->885850375
mautrix-telegram_1           | Traceback (most recent call last):
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 368, in _catch
mautrix-telegram_1           |     await task
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.
mautrix-telegram_1           | [2020-12-09 08:08:25,306] [ERROR@mau.user.@juniorjpdj:juniorjpdj.pl] Error while backfilling 388773942<->370300617
mautrix-telegram_1           | Traceback (most recent call last):
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 368, in _catch
mautrix-telegram_1           |     await task
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.
mautrix-telegram_1           | [2020-12-09 08:08:25,361] [ERROR@mau.user.@juniorjpdj:juniorjpdj.pl] Error while backfilling 388773942<->627815744
mautrix-telegram_1           | Traceback (most recent call last):
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 368, in _catch
mautrix-telegram_1           |     await task
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 444, in backfill
mautrix-telegram_1           |     await self._locked_backfill(source, is_initial, limit, last_id)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 484, in _locked_backfill
mautrix-telegram_1           |     await self._backfill(source, min_id, limit)
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/mautrix_telegram/portal/telegram.py", line 500, in _backfill
mautrix-telegram_1           |     async with client.takeout(**self._takeout_options) as takeout:
mautrix-telegram_1           |   File "/usr/lib/python3.8/site-packages/telethon/client/account.py", line 44, in __aenter__
mautrix-telegram_1           |     raise ValueError("Can't send a takeout request while another "
mautrix-telegram_1           | ValueError: Can't send a takeout request while another takeout for the current session still not been finished yet.
```
It came back ;/

**Comment by hieronymousch** [comment]
same issue here...

**Comment by JuniorJPDJ** [comment]
Still getting them, now set `takeout_limit: 9999999999999` as workaround.
