### ISSUE TITLE
Db url is treated as invalid

### ISSUE THREAD

**Issue by L0ric0** [mautrix/telegram#544]
on version 0.9 i get the following error:

```
mau.init[276805]: [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/util/program.py", line 93, in _prepare
    self.prepare()
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 81, in prepare
    self.prepare_bridge()
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix_telegram/__main__.py", line 85, in prepare_bridge
    self.matrix = context.mx = MatrixHandler(context)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix_telegram/matrix.py", line 48, in __init__
    super().__init__(command_processor=com.CommandProcessor(context), bridge=context.bridge)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 68, in __init__
    db_url=self._get_db_url(bridge.config),
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 76, in _get_db_url
    parsed_url = URL(db_url)
  File "/opt/matrix/mautrix-telegram/lib/python3.8/site-packages/yarl/__init__.py", line 144, in __new__
    val = urlsplit(val)
  File "/usr/lib/python3.8/urllib/parse.py", line 464, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

The database url should be fine as it was not changed from previous versions

**Comment by tulir** [comment]
It's probably invalid if urllib says so :thinking:

**Comment by L0ric0** [comment]
the problem is that the db password contains special characters which urllib has started to not like. chaneging the postgress password to one that contains only alphanumerics fixed the issue.

It would probably be nice to document this somewhere or properly encode all chars
