### ISSUE TITLE
Error while doing login-matrix via web login

### ISSUE THREAD

**Issue by LotusAxt** [mautrix/telegram#568]
I get a http 500 status code, when I try to do the matrix login via web.
After the 500 code, the login seems to work, but will get lost when restarting the bridge.

```
[2021-01-04 17:45:43,164] [INFO@mau.puppet.295163816] Initialized custom mxid: @siplex:savemy.name. Starting sync task
[2021-01-04 17:45:43,169] [WARNING@mau.puppet.295163816] Error when leaving rooms with default user
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 208, in switch_mxid
    await self._leave_rooms_with_default_user()
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 267, in _leave_rooms_with_default_user
    if await self.default_puppet_should_leave_room(room_id):
TypeError: object bool can't be used in 'await' expression
[2021-01-04 17:45:43,173] [ERROR@aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/web/public/__init__.py", line 150, in post_matrix_login
    return await self.post_matrix_token(user, data["value"])
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/web/common/auth_api.py", line 62, in post_matrix_token
    await puppet.switch_mxid(token.strip(), user.mxid)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/custom_puppet.py", line 211, in switch_mxid
    await self.save()
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/puppet.py", line 174, in save
    self.db_instance.edit(**self._fields)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 159, in edit
    .values(**values))
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 3 - probably unsupported type.
[SQL: UPDATE puppet SET custom_mxid=?, access_token=?, next_batch=?, base_url=?, displayname=?, displayname_source=?, username=?, photo_id=?, is_bot=?, matrix_registered=?, disable_updates=? WHERE puppet.id = ?]
[parameters: (<update sqlStatement removed>)]
(Background on this error at: http://sqlalche.me/e/13/rvf5)

```
I removed the sql statement in "[parameters: (<update sqlStatement removed>)]" as it contains private information like the matrix access token. If its necessary for debugging I could send it to you directly.

Best Regards and thank you for your work.

**Comment by tulir** [comment]
Only the access token is private, the rest aren't. The third parameter (after access token) is probably the one that broke

**Comment by LotusAxt** [comment]
Sorry for the late response, it was a busy week. Here is the parameter part of the SQL statement:
`[parameters: ('@siplex:savemy.name', '<Matrix access token removed>', 's105448_156728_463_17181_1887_3_1151_9462_17', URL('https://savemy.name'), 'Rafael (Telegram)', 1468359093, 'Thodrin', '1267718937138800555', 0, 1, 0, 295163816)]`

I hope this helps. Let me know if you need further information.

**Comment by petabyteboy** [comment]
I'm seeing the same issue, also 500 status code, after that it works until the next restart.
