### ISSUE TITLE
not able to run mautrix-telegram

### ISSUE THREAD

**Issue by rohitmp** [mautrix/telegram#571]
I have followed all the steps in https://github.com/tulir/mautrix-telegram/wiki/Bridge-setup
and i keep getting below error.
Setup details
mautrix-telegram version: 0.9.0
(telegram) telegram# python -V
Python 3.8.7

Matrix version: 1.3.1
matrix python version is: Python 3.5.2

please help me by pointing out what could be wrong..? 

error log:

python -m mautrix_telegram
[INFO@mau.init] Initializing mautrix-telegram 0.9.0
[INFO@mau.init] Initialization complete in 0.48 seconds
[DEBUG@mau.init] Running startup actions...
[DEBUG@mau.init] Starting appservice...
[DEBUG@mau.as] Starting appservice web server on 127.0.0.1:29317
[INFO@mau.mx] Ensuring connectivity to homeserver
[DEBUG@mau.mx] Whoami endpoint returned M_FORBIDDEN, trying to register bridge bot before retrying...
[CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 89, in wait_for_connection
    await self.az.intent.whoami()
  File "/telegram/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
    resp = await self.api.request(Method.GET, Path.account.whoami)
  File "/telegram/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/telegram/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: Application service has not registered this user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 355, in ensure_registered
    await self._register()
  File "/telegram/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/telegram/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MExclusive: Invalid user localpart for this application service.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/telegram/lib/python3.8/site-packages/mautrix/util/program.py", line 190, in _run
    self.loop.run_until_complete(self.start())
  File "/3.8.7/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/telegram/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 148, in start
    await self.matrix.wait_for_connection()
  File "/telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 95, in wait_for_connection
    await self.az.intent.ensure_registered()
  File "/telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 358, in ensure_registered
    raise IntentError(f"Failed to register {self.mxid}", e)

**Comment by aermike** [comment]
cd virtualenv
python -m mautrix_telegram -g
acording with this instructions
https://docs.mau.fi/bridges/python/setup/index.html?bridge=telegram

**Comment by luochen1990** [comment]
@rohitmp Have you solved this problem?   And could you please share the steps?
