### ISSUE TITLE
allow to set bridge.login_shared_secret_map with env var

### ISSUE THREAD

**Issue by ghost** [mautrix/telegram#584]
https://github.com/tulir/mautrix-telegram/pull/332 added the possibility to set config variables with environment variables. This made it possible to pass secrets to mautrix-telegram in cases where the config file is world-readable (like NixOS).
In 0.9.0 the `bridge.login_shared_secret` config option was changed to `bridge.login_shared_secret_map` where a secret can now be specified for each server.
However it's not possible anymore to set the secret via an environment variable.

**Comment by petabyteboy** [comment]
CC @pacien @CRTified

**Comment by pacien** [comment]
Substituting settings with their value from the corresponding environment variable at access time like for other keys doesn't seem to be possible for dictionary and list objects since they are iterated over in other places in the code.

Instead, we might have to populate those collections, and maybe the whole configuration object, at initialisation time, when the `copy()` are happening in `Config.do_update()`, or better, in that `copy()` utility function from Mautrix Python. We would however need to be able to specify both a different prefix for the keys, but also the desired type (dict, list, others).

@tulir: What do you think?

**Comment by tulir** [comment]
The environment variable values can now be prefixed with `json::` to have it be parsed as JSON, so login_shared_secret_map can be set with something like

```
MAUTRIX_TELEGRAM_BRIDGE_LOGIN_SHARED_SECRET_MAP=json::{"example.com":"secret"}

**Comment by Luflosi** [comment]
@tulir has this ever ben tested? When I tried to use this and start mautrix-telegram, I got
```
Traceback (most recent call last):
  File "/nix/store/wznvmsimfdfdx7cr800aq3alnxhmss2z-python3.10-mautrix-telegram-0.12.2/bin/.mautrix-telegram-wrapped", line 6, in <module>
    from mautrix_telegram.__main__ import main
  File "/nix/store/wznvmsimfdfdx7cr800aq3alnxhmss2z-python3.10-mautrix-telegram-0.12.2/lib/python3.10/site-packages/mautrix_telegram/__main__.py", line 144, in <module>
    TelegramBridge().run()
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 91, in run
    self._prepare()
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 97, in _prepare
    self.preinit()
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 112, in preinit
    super().preinit()
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 117, in preinit
    self.prepare_config()
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 133, in prepare_config
    self.config = self.config_class(
  File "/nix/store/vzl290qf0zbcbznhv3lcrv8fsvsa6v2q-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/config.py", line 49, in __init__
    value = json.loads(value)
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I tried to fix this with the following patch to mautrix:
```diff
diff --git a/mautrix/bridge/config.py b/mautrix/bridge/config.py
index 16d8f6a..c59145a 100644
--- a/mautrix/bridge/config.py
+++ b/mautrix/bridge/config.py
@@ -46,7 +46,7 @@ class BaseBridgeConfig(BaseFileConfig, BaseValidatableConfig, ABC):
                     continue
                 key = key.removeprefix(env_prefix)
                 if value.startswith("json::"):
-                    value = json.loads(value)
+                    value = json.loads(value.removeprefix("json::"))
                 self.env[key] = value
 
     def __getitem__(self, item: str) -> Any:
```
With this patch mautrix-telegram also fails to start:
```
Traceback (most recent call last):
  File "/nix/store/cy90qml004851ivrddp6mi84ml47k09d-python3.10-mautrix-telegram-0.12.2/bin/.mautrix-telegram-wrapped", line 6, in <module>
    from mautrix_telegram.__main__ import main
  File "/nix/store/cy90qml004851ivrddp6mi84ml47k09d-python3.10-mautrix-telegram-0.12.2/lib/python3.10/site-packages/mautrix_telegram/__main__.py", line 144, in <module>
    TelegramBridge().run()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 91, in run
    self._prepare()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 97, in _prepare
    self.preinit()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 112, in preinit
    super().preinit()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 117, in preinit
    self.prepare_config()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 141, in prepare_config
    self.load_and_update_config()
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/program.py", line 156, in load_and_update_config
    self.config.update(save=not self.args.no_update)
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/config/base.py", line 76, in update
    self.do_update(ConfigUpdateHelper(base, self))
  File "/nix/store/cy90qml004851ivrddp6mi84ml47k09d-python3.10-mautrix-telegram-0.12.2/lib/python3.10/site-packages/mautrix_telegram/config.py", line 132, in do_update
    copy("bridge.login_shared_secret_map")
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/util/config/base.py", line 28, in copy
    val = self.source[from_path]
  File "/nix/store/3vkvg63wmw35yyjlzzn9v7xzbivaymi9-python3.10-mautrix-0.18.8/lib/python3.10/site-packages/mautrix/bridge/config.py", line 60, in __getitem__
    if val.startswith("json::"):
AttributeError: 'dict' object has no attribute 'startswith'
```
so I expanded the patch:
```diff
diff --git a/mautrix/bridge/config.py b/mautrix/bridge/config.py
index 16d8f6a..6b3844d 100644
--- a/mautrix/bridge/config.py
+++ b/mautrix/bridge/config.py
@@ -46,7 +46,7 @@ class BaseBridgeConfig(BaseFileConfig, BaseValidatableConfig, ABC):
                     continue
                 key = key.removeprefix(env_prefix)
                 if value.startswith("json::"):
-                    value = json.loads(value)
+                    value = json.loads(value.removeprefix("json::"))
                 self.env[key] = value
 
     def __getitem__(self, item: str) -> Any:
@@ -57,7 +57,7 @@ class BaseBridgeConfig(BaseFileConfig, BaseValidatableConfig, ABC):
             except KeyError:
                 pass
             else:
-                if val.startswith("json::"):
+                if isinstance(val, str) and val.startswith("json::"):
                     val = json.loads(val.removeprefix("json::"))
                 return val
         return super().__getitem__(item)
```
This seems to work so far but I'm not sure if it's the correct way to fix this.
Does this seem reasonable? If so, I can create a PR.
Or did I do something wrong?

**Comment by Luflosi** [comment]
I see that https://github.com/mautrix/python/commit/f6b10699c16b90bf763614014a94d35e24a1efd7 was created about an hour after my comment above. It would have been nice to know that this has been fixed. I only noticed because my patch didn't apply anymore.
Anyways, thanks for the quick fix!
