### ISSUE TITLE
Unhandled error while handling command `clear-db-cache puppet`

### ISSUE THREAD

**Issue by rakshazi** [mautrix/telegram#620]
Hello,

bridge configured with [spantaleev/matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy).

When sending `clear-db-cache puppet` message from user with admin level permissions I get that error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 404, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 289, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/portal/admin.py", line 40, in clear_db_cache
    puppet.sync_task.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
```

**Comment by rakshazi** [comment]
@tulir could you link a commit/PR that fixes the issue, please?

It still exists for me, will it be fixed with update to some version

**Comment by tulir** [comment]
It's https://github.com/mautrix/telegram/commit/89ab29ea5f6e827230c1f5fccbfcc70281df0349, but you probably shouldn't be using that command anyway
