### ISSUE TITLE
MatrixConnectionError: Cannot connect to host

### ISSUE THREAD

**Issue by Maximilian-Staab** [mautrix/telegram#653]
# Bridge Connectivity Issue - ConnectionResetError ClientConnectionError MatrixConnectionError

I'm having connectivity issues after updating all matrix related services. 
I also changed my "A" DNS IP entry recently, could that have something to do with this? **Could the old IP still be cached somewhere?**
My whole setup is using nginx as a proxy and the ".well-known" files, but they didn't change at all.

All my bridges stopped working after the most recent update (mautrix-whatsapp/telegram/signal), all with the same issue. I'm using this issue board because the log entries are more verbose in the telegram bridge.

## Telegram
```
mautrix-telegram    | [2021-08-12 10:22:49,252] [WARNING@mau.as.api.bot] Request #7 failed with Cannot connect to host mydomain.com:443 ssl:default [None], retrying in 4 seconds
mautrix-telegram    | [2021-08-12 10:22:53,287] [WARNING@mau.as.api.bot] Request #7 failed with Cannot connect to host mydomain.com:443 ssl:default [None], retrying in 8 seconds
mautrix-telegram    | [2021-08-12 10:23:01,344] [WARNING@mau.as.api.bot] Request #7 failed with Cannot connect to host mydomain.com:443 ssl:default [None], retrying in 16 seconds
mautrix-telegram    | [2021-08-12 10:23:17,409] [WARNING@mau.as.api.bot] Request #7 failed with Cannot connect to host mydomain.com:443 ssl:default [None], retrying in 32 seconds
mautrix-telegram    | [2021-08-12 10:23:49,513] [CRITICAL@mau.init] Unexpected error in main event loop
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
mautrix-telegram    |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
mautrix-telegram    |   File "/usr/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
mautrix-telegram    |     transport, protocol = await self._create_connection_transport(
mautrix-telegram    |   File "/usr/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
mautrix-telegram    |     await waiter
mautrix-telegram    | ConnectionResetError
mautrix-telegram    |
mautrix-telegram    | The above exception was the direct cause of the following exception:
mautrix-telegram    |
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
mautrix-telegram    |     return await self._send(method, full_url, content, query_params, headers or {})
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 171, in _send
mautrix-telegram    |     async with request as response:
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
mautrix-telegram    |     self._resp = await self._coro
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
mautrix-telegram    |     conn = await self._connector.connect(
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
mautrix-telegram    |     proto = await self._create_connection(req, traces, timeout)
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
mautrix-telegram    |     _, proto = await self._create_direct_connection(req, traces, timeout)
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
mautrix-telegram    |     raise last_exc
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
mautrix-telegram    |     transp, proto = await self._wrap_create_connection(
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
mautrix-telegram    |     raise client_error(req.connection_key, exc) from exc
mautrix-telegram    | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mydomain.com:443 ssl:default [None]
mautrix-telegram    |
mautrix-telegram    | The above exception was the direct cause of the following exception:
mautrix-telegram    |
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 190, in _run
mautrix-telegram    |     self.loop.run_until_complete(self.start())
mautrix-telegram    |   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
mautrix-telegram    |     return future.result()
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 156, in start
mautrix-telegram    |     await self.matrix.wait_for_connection()
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 101, in wait_for_connection
mautrix-telegram    |     await self.az.intent.whoami()
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
mautrix-telegram    |     resp = await self.api.request(Method.GET, Path.account.whoami)
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 271, in request
mautrix-telegram    |     raise MatrixConnectionError(str(e)) from e
mautrix-telegram    | mautrix.errors.base.MatrixConnectionError: Cannot connect to host mydomain.com:443 ssl:default [None]
```

## Whatsapp
```
"https://mydomain.com/_matrix/client/r0/account/whoami?user_id=%40whatsapp%3Amydomain.com": EOF
```

## Signal

Same as with telegram.

## Nginx

```
2021/08/12 09:51:15 [error] 4221#4221: *417 connect() failed (111: Connection refused) while connecting to upstream, client: <ipv6 removed>, server: mydomain.com, request: "OPTIONS /_matrix/client/r0/presence/%40username%3Amydomain.com/status HTTP/1.1", upstream: "http://192.168.0.207:8008/_matrix/client/r0/presence/%40username%3Amydomain.com/status", host: "mydomain.com"
2021/08/12 09:51:15 [error] 4221#4221: *419 connect() failed (111: Connection refused) while connecting to upstream, client: <ipv6 removed>, server: mydomain.com, request: "OPTIONS /_matrix/client/r0/rooms/!BehvzPKtzzljgmKxTR%3Amydomain.com/read_markers HTTP/1.1", upstream: "http://192.168.0.207:8008/_matrix/client/r0/rooms/!BehvzPKtzzljgmKxTR%3Amydomain.com/read_markers", host: "mydomain.com"
2021/08/12 09:51:15 [error] 4221#4221: *421 connect() failed (111: Connection refused) while connecting to upstream, client: <ipv6 removed>, server: mydomain.com, request: "OPTIONS /_matrix/client/r0/user/%40username%3Amydomain.com/account_data/im.vector.setting.breadcrumbs HTTP/1.1", upstream: "http://192.168.0.207:8008/_matrix/client/r0/user/%40username%3Amydomain.com/account_data/im.vector.setting.breadcrumbs", host: "mydomain.com"
2021/08/12 09:51:16 [error] 4221#4221: *424 connect() failed (111: Connection refused) while connecting to upstream, client: <ipv6 removed>, server: mydomain.com, request: "OPTIONS /_matrix/client/r0/user/%40username%3Amydomain.com/account_data/im.vector.setting.breadcrumbs HTTP/1.1", upstream: "http://192.168.0.207:8008/_matrix/client/r0/user/%40username%3Amydomain.com/account_data/im.vector.setting.breadcrumbs", host: "mydomain.com"
```

**Comment by Maximilian-Staab** [comment]
Found the issue:

This was a problem with my ipv4 to ipv6 relay server (to bypass a limitation of my ISP) not working properly.
