### ISSUE TITLE
No longer able to start bridge: Ran out of Input

### ISSUE THREAD

**Issue by jannis3005** [mautrix/telegram#664]
Hi,

i can no longer start the bridge, after updating (git pull, alembic upgrade head, and pip install --upgrade git+https://github.com/mautrix/telegram.git#egg=mautrix-telegram[all]) I just get an error when trying to start the bridge. However, looking at the mentioned code lines, I cannot figure out where the problem lies,

<details>
<summary>./start.sh</summary>
```

[2021-09-22 17:43:55,599] [INFO@mau.init] Initializing mautrix-telegram 0.10.1+dev.5dea5977
[2021-09-22 17:43:55,728] [INFO@mau.init] Initialization complete in 1.12 seconds
[2021-09-22 17:43:55,729] [DEBUG@mau.init] Running startup actions...
[2021-09-22 17:43:55,730] [DEBUG@mau.init] Starting appservice...
[2021-09-22 17:43:55,732] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29317
[2021-09-22 17:43:55,736] [INFO@mau.mx] Ensuring connectivity to homeserver
[2021-09-22 17:43:55,839] [DEBUG@mau.bridge.e2ee] Logging in with bridge bot user
[2021-09-22 17:43:55,840] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/program.py", line 190, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/bridge.py", line 167, in start
    await self.matrix.init_encryption()
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 147, in init_encryption
    await self.e2ee.start()
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/bridge/e2ee.py", line 183, in start
    await self.crypto_store.open()
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/file_store.py", line 81, in open
    self._load()
  File "/home/pi/synapse/bridges/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/file_store.py", line 72, in _load
    self.deserialize(self.filer.load(file))
EOFError: Ran out of input

```

**Comment by tulir** [comment]
Don't use pickle for the crypto db (also don't use sqlite for the main db, only postgres will be supported in the future)

**Comment by pludi** [comment]
Encountered the same issue. Is there any actual solution besides "Reset the DB, better luck next time"?

**Comment by tulir** [comment]
No, the pickle db can explode at any time, that's why it shouldn't be used.

**Comment by pludi** [comment]
But I didn't use the pickle db, I explicitly configured the SQLite DB.
