### ISSUE TITLE
Bridge exception

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#671]
Trying to bridge room with no regular writing permissions for all users

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/portal/bridge.py", line 160, in confirm_bridge
    await _locked_confirm_bridge(evt, portal=portal, room_id=bridge_to_mxid,
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/portal/bridge.py", line 194, in _locked_confirm_bridge
    await warn_missing_power(levels, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/portal/util.py", line 56, in warn_missing_power
    await evt.reply("Warning: The bot does not have privileges to redact messages on Matrix. "
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 95, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 282, in send_message_event
    return await super().send_message_event(room_id, event_type, content, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/events.py", line 314, in send_message_event
    resp = await self.api.request(Method.PUT, url, content, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 171, in _send
    async with request as response:
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Comment by tulir** [comment]
Doesn't seem like a bridge issue, but the bridge bot should probably have write permissions
