### ISSUE TITLE
Bridging to new Telegram Room not possible - bigint out of range

### ISSUE THREAD

**Issue by valvanet** [mautrix/telegram#675]
I'm getting this error after successfully logging in with my Telegram Bot and trying to bridge to a newly created Telegram-Chat from within Matrix.
 
I'm running Postgres v13 via docker-compose and the "latest" branch of the mautrix-telegram docker-container.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NumericValueOutOfRange: bigint out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 409, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 296, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/portal/bridge.py", line 67, in bridge
    portal = po.Portal.get_by_tgid(tgid, peer_type=peer_type)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/base.py", line 440, in get_by_tgid
    portal.db_instance.insert()
  File "/usr/lib/python3.9/site-packages/mautrix/util/db/base.py", line 199, in insert
    conn.execute(self.t.insert().values(**self._insert_values))
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) bigint out of range

[SQL: INSERT INTO portal (tgid, tg_receiver, peer_type, megagroup, mxid, avatar_url, encrypted, config, username, title, about, photo_id) VALUES (%(tgid)s, %(tg_receiver)s, %(peer_type)s, %(megagroup)s, %(mxid)s, %(avatar_url)s, %(encrypted)s, %(config)s, %(username)s, %(title)s, %(about)s, %(photo_id)s)]
[parameters: {'tgid': 9501995446686482547, 'tg_receiver': 9501995446686482547, 'peer_type': 'channel', 'megagroup': False, 'mxid': None, 'avatar_url': None, 'encrypted': False, 'config': '{}', 'username': None, 'title': None, 'about': None, 'photo_id': None}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)

```

I'm guessing the amount of new Telegram-Channels is huge, so maybe saving the Channel-ID in a bigint could exceed the limits. (?)

Can I fix the issue within a docker environment?
Any help is appreciated.
Have a nice one!

o/

**Comment by valvanet** [comment]
Nevermind, i used the wrong part of the ID, which is much longer than the right one.

(c1503336342_9501995446686482547)
