### ISSUE TITLE
Cant sync chats

### ISSUE THREAD

**Issue by cofob** [mautrix/telegram#679]
Hello! When I try to `!tg sync` I get this error. Installed from [ansible role](https://matrix.org/docs/projects/other/matrix-docker-ansible-deploy).
```
Unhandled error while handling command:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "user" violates foreign key constraint "contact_user_fkey" on table "contact"
DETAIL:  Key (tgid)=(1911924821) is still referenced from table "contact".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 291, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/misc.py", line 203, in sync
    await evt.sender.sync_dialogs()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 541, in sync_dialogs
    await self.save(portals=True)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 169, in save
    self.db_instance.edit(tgid=self.tgid, tg_username=self.username, tg_phone=self.phone,
  File "/usr/lib/python3.9/site-packages/mautrix/util/db/base.py", line 159, in edit
    conn.execute(self.t.update()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "user" violates foreign key constraint "contact_user_fkey" on table "contact"
DETAIL:  Key (tgid)=(1911924821) is still referenced from table "contact".

[SQL: UPDATE "user" SET tgid=%(tgid)s, tg_username=%(tg_username)s, tg_phone=%(tg_phone)s, saved_contacts=%(saved_contacts)s WHERE "user".mxid = %(mxid_1)s]
[parameters: {'tgid': 1457408124, 'tg_username': 'cofob', 'tg_phone': '12345678', 'saved_contacts': 0, 'mxid_1': '@cofob:cofob.ru'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

**Comment by tulir** [comment]
This probably won't happen the same way anymore (although something else might break)
