### ISSUE TITLE
login: Unhandled exception while sending code

### ISSUE THREAD

**Issue by V02460** [mautrix/telegram#685]
When trying to login via the bridge bot chat flow, i.e., entering *login* followed by a phone number and the received SMS verification code, the bot answers with:
```
Unhandled exception while sending code. Check console for more details.
```
The bridge logs show these two errors:
```
mau.commands: Error sending phone code                                                                                                                           
Traceback (most recent call last):                                                                                                                               
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/auth.py", line 280, in enter_code                                                    
    await _sign_in(evt, code=evt.args[0])                                                                                                                        
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/auth.py", line 313, in _sign_in                                                      
    user = await login_as.client.sign_in(**sign_in_info)                                                                                                         
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 372, in sign_in
```
```
mau.commands: Error sending phone code
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/auth.py", line 280, in enter_code
    await _sign_in(evt, code=evt.args[0])
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/auth.py", line 313, in _sign_in
    user = await login_as.client.sign_in(**sign_in_info)
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 372, in sign_in
    raise errors.PhoneNumberUnoccupiedError(request=request)
telethon.errors.rpcerrorlist.PhoneNumberUnoccupiedError: The phone number is not yet being used (caused by SignInRequest)
```
The Telegram account in question was active on the bridge before.

**Comment by DDvO** [comment]
I have essentially the same issue, getting this useless error message on the client side.
Looks like my Matrix user address is not accepted because I had connected it before to some other telegram bridge bot.
Note that the telegrambot log contains `User is already connected!`
Das Telegram not like being connected to more than one bridge?
In any case, the client-side error message should be more informative.

```
[2025-02-16 19:38:43,034] [ERROR@telethon.7956688466768944615.network.mtprotosender] Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: InvokeWithLayerRequest(layer=183, query=InitConnectionRequest(api_id=8073176532, device_model='mautrix-telegram', system_version='1.37.0a1', app_version='0.15.2', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))
[2025-02-16 19:38:43,035] [ERROR@mau.user.@....] Exception connecting to Telegram, retrying in 5s...
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/mautrix_telegram/abstract_user.py", line 331, in start
    await self.client.connect()
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 584, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/tl/functions/__init__.py", line 357, in _bytes
    self.query._bytes(),
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/telethon/tl/functions/__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
[2025-02-16 19:38:48,044] [INFO@telethon.7956688466768944615.network.mtprotosender] User is already connected!
[2025-02-16 19:38:48,044] [DEBUG@mau.user.@....] @... connected: True
[2025-02-16 19:38:48,180] [ERROR@mau.user.@.....] Unknown RPC error in start(): <class 'telethon.errors.rpcerrorlist.ConnectionNotInitedError'>: Connection not initialized (caused by GetStateRequest)
[2025-02-16 19:38:48,269] [ERROR@mau.commands] Error requesting phone code
```
