### ISSUE TITLE
crash at search

### ISSUE THREAD

**Issue by progserega** [mautrix/telegram#688]
1. I have installed mautrix-telegram 0.6.1
2. bridge was work properly
3. User, which not in my contact list - send message to me
4. I do not get this message in matrix
5. Try "sync", "sync contacts" in bot chat, try sync contacts in google account in android phone (where installed telegram), but this was not help: today I receive crashs in telegram bridge by many commands (sync, search).

I am send command to "Telegram bridge bot": 'search -r Aleksandra' and receive chash:

[mautrix-telegram.log](https://github.com/mautrix/telegram/files/7492365/mautrix-telegram.log)

**Comment by progserega** [comment]
As see in logs - problem with @telegram_794339248 user. From other users I success receive messages and success send messages to all other users - so bridge break only for this user.

**Comment by progserega** [comment]
'sync' command receive such log error in chat:

```
Traceback (most recent call last):
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_appservice/intent_api.py", line 887, in ensure_joined
    await self._join_room_direct(room_id)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
    errcode=errcode, message=message)
mautrix_appservice.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_appservice/intent_api.py", line 894, in ensure_joined
    await self._join_room_direct(room_id)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
    errcode=errcode, message=message)
mautrix_appservice.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/commands/handler.py", line 352, in handle
    await handler(evt)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/commands/handler.py", line 274, in __call__
    return await self._handler(evt)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/commands/telegram/misc.py", line 162, in sync
    await evt.sender.sync_dialogs(synchronous_create=True)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/user.py", line 312, in sync_dialogs
    await asyncio.gather(*creators, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 343, in create_matrix_room
    await update
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 324, in update_matrix_room
    await self.sync_telegram_users(user, users)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_telegram/portal.py", line 502, in sync_telegram_users
    await puppet.intent.ensure_joined(self.mxid)
  File "/opt/mautrix_telegram/lib/python3.5/site-packages/mautrix_appservice/intent_api.py", line 897, in ensure_joined
    raise IntentError("Failed to join room {} as {}".format((room_id), (self.mxid)), e2)
mautrix_appservice.errors.IntentError: Failed to join room !CallzhIdlzZrSHuDxsd:matrix-bridge.rsprim.ru as @telegram_512441193:matrix-bridge.rsprim.ru
```

**Comment by tulir** [comment]
> 0.6.1

...that's over 2 years old
