### ISSUE TITLE
Matrix side of the bridge doesn't accept invite

### ISSUE THREAD

**Issue by nkukard** [mautrix/telegram#689]
I seem to be having some kind of an issue inviting the matrix bot to a room, I've already got 2 rooms setup about a year ago, but I tried to add another today and got the below error.

Perhaps someone can point me in the right direction?

```
  matrix_chat_[redacted]_com-mautrix-telegram-1  | [2021-11-09 10:30:35,700] [ERROR@mau.mx] Failed to join room !dQttnbuuODXKkzWMVG:[redacted] with bridge bot, retrying in 50 seconds...
  matrix_chat_[redacted]_com-mautrix-telegram-1  | Traceback (most recent call last):
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 392, in ensure_registered
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     await self._register()
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 205, in request
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     return await self._send(method, endpoint, content, query_params, headers or {})
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 144, in _send
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     raise make_request_error(http_status=response.status,
  matrix_chat_[redacted]_com-mautrix-telegram-1  | mautrix.errors.request.MUnknown: An access token should not be provided on requests to /register (except if type is m.login.application_se  rvice)
  matrix_chat_[redacted]_com-mautrix-telegram-1  | During handling of the above exception, another exception occurred:
  matrix_chat_[redacted]_com-mautrix-telegram-1  | Traceback (most recent call last):
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 167, in accept_bot_invite
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     await self.az.intent.join_room(room_id)
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 74, in wrapper
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     await __self.ensure_registered()
  matrix_chat_[redacted]_com-mautrix-telegram-1  |   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 395, in ensure_registered
  matrix_chat_[redacted]_com-mautrix-telegram-1  |     raise IntentError(f"Failed to register {self.mxid}", e)
  matrix_chat_[redacted]_com-mautrix-telegram-1  | mautrix.errors.base.IntentError: ('Failed to register @telegrambot:[redacted]', MUnknown('An access token should not be provided on reques  ts to /register (except if type is m.login.application_service)'))
```

**Comment by tulir** [comment]
Sounds like an outdated version of the bridge

**Comment by tulir** [comment]
That has never been the official image path. It was previously `dock.mau.dev/tulir/mautrix-telegram` and recently moved to `dock.mau.dev/mautrix/telegram` (as mentioned in the v0.10.1 release notes)

**Comment by nkukard** [comment]
I see the problem, thanks!
