### ISSUE TITLE
Bridge kicked me from telegram portals while I haven't left the telegram chat rooms

### ISSUE THREAD

**Issue by bnjbvr** [mautrix/telegram#703]
I'm hosting the bridge via Docker, and i've been using the most up to date version (upgraded yesterday, following a synapse upgrade too). On Matrix I've been in a portal room to a conversation with 3 other peoples. While I haven't left that conversation in Telegram, the bot thought I did so and kicked me out of it. I can't join it anymore, because the room is invite only, and even forgetting the portal room and asking the Telegram bot to `sync` doesn't seem to help.

I've got another user on my server using the same instance of the Telegram bridge who's suffering the same issues, for at least a few conversations. It's not _all_ of them that aren't working anymore, just a few ones, but the fact that it's happening more and more often is a bit concerning.

Is there anything I can do to join those conversations back?

**Comment by JuniorJPDJ** [comment]
try `!tg sync` or bridge restart

**Comment by bnjbvr** [comment]
Thanks, I've tried both but that didn't make the room reappear. Wonder if should remove the room in the tg admin room, so it recreates it and re invite me.

**Comment by bnjbvr** [comment]
For what it's worth, I started clearing caches, removing empty rooms, etc. and re-sync'ing, I'm now getting an error in the Telegram bot room:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "user_portal" violates foreign key constraint "user_portal_portal_fkey"
DETAIL:  Key (portal, portal_receiver)=(302668004, 302668004) is not present in table "portal".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 407, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 293, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/misc.py", line 203, in sync
    await evt.sender.sync_dialogs()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 572, in sync_dialogs
    await self.save(portals=True)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 177, in save
    self.db_instance.portals = self.db_portals
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/db/user.py", line 83, in portals
    conn.execute(UserPortal.t.insert(), insert_portals)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "user_portal" violates foreign key constraint "user_portal_portal_fkey"
DETAIL:  Key (portal, portal_receiver)=(302668004, 302668004) is not present in table "portal".
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

Anyways, I keep on getting kicked out of rooms, and now some new Telegram rooms never get portaled in Matrix. Unfortunately, that makes it so that I can't rely on the bridge anymore, since there might be conversations I am missing, and using both doesn't quite make sense as it defeats the purpose of the bridge. Good luck!

**Comment by aiomaster** [comment]
I have seen the same, but only for a specific room containing some special chars in its name like this: 🌈  💐
Maybe this could be the cause of the problem and there is some weird matching of the name somewhere that isn't working?

**Comment by tulir** [comment]
This was probably the minigroup member sync bug

**Comment by bnjbvr** [comment]
Confirmed! After upgrading to the latest docker image and re-instantiating the Docker instance, I've been re-invited to all the groups I've been ejected from before. Thanks a bunch @tulir :star_struck:
