### ISSUE TITLE
as_handler.py: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by jaller94** [mautrix/telegram#708]
We have a bridge where this happens approximately hourly.

```
[2021-12-16 14:08:46,907] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/as_handler.py", line 204, in try_handle
    await handler_func(event)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 594, in int_handle_event
    await self.handle_join(evt.room_id, UserID(evt.state_key), evt.event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/matrix.py", line 147, in handle_join
    await portal.join_matrix(user, event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 177, in join_matrix
    await self._send_state_change_message("join", user, event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 86, in _send_state_change_message
    message = await self._get_state_change_message(event, user, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 65, in _get_state_change_message
    tpl = self.get_config(f"state_event_formats.{event}")
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/base.py", line 219, in get_config
    local = util.recursive_get(self.local_config, key)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/recursive_dict.py", line 40, in recursive_get
    return recursive_get(next_data, next_key)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/recursive_dict.py", line 41, in recursive_get
    return data.get(key, None)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by tulir** [comment]
This probably means someone set an invalid config in the room using `!tg config`, the room-specific configs aren't really validated at all currently.
