### ISSUE TITLE
Image processing crashes occasionally

### ISSUE THREAD

**Issue by theCalcaholic** [mautrix/telegram#709]
For some reason, processing image processing tends to crash often but not always when sending images from FluffyChat to Telegram (tested on Android).
I have observed the logs of the bridge and found the following exception, which unfortunately lacks a precise cause:

```
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]: [2021-12-16 17:25:46,328] [ERROR@mau.as] Exception in Matrix event handler
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]: Traceback (most recent call last):
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/as_handler.py", line 204, in try_handle
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await handler_func(event)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 590, in int_handle_event
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await self.handle_encrypted(evt)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 458, in handle_encrypted
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await self.int_handle_event(decrypted)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 588, in int_handle_event
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 348, in handle_message
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await portal.handle_matrix_message(sender, message, event_id)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 373, in handle_matrix_message
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await self._handle_matrix_message(sender, content, event_id)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 421, in _handle_matrix_message
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     await self._handle_matrix_file(sender_id, event_id, space, client, content, reply_to,
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/matrix.py", line 307, in _handle_matrix_file
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     response = await client.send_media(self.peer, media, reply_to=reply_to,
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/mautrix_telegram/tgclient.py", line 55, in send_media
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     return self._get_response_message(request, await self(request), entity)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     return await self._call(self._sender, request, ordered=ordered)
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:   File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]:     result = await future
Dez 16 18:25:46 REDACTED-SERVER-URL matrix-mautrix-telegram[5572]: telethon.errors.rpcerrorlist.ImageProcessFailedError: Failure while processing image (caused by SendMediaRequest)
```

Version of mautrix-telegram: Docker, dock.mau.dev/mautrix/telegram:v0.10.2
Version of FluffyChat: 1.1.0

**Comment by Guest0x0** [comment]
I spot this when using other clients too. More specifically when using `nheko` on NixOS and `fluffyChat` on iOS.

**Comment by tulir** [comment]
Looks like fluffychat encrypts attachments in a non-spec-compliant way, I'd guess nheko does too

**Comment by theCalcaholic** [comment]
@tulir Thank you for looking into this. I'll report it upstream :+1:

**Comment by theCalcaholic** [comment]
For reference: https://gitlab.com/famedly/fluffychat/-/issues/887
