### ISSUE TITLE
see errors

### ISSUE THREAD

**Issue by pilikan33** [mautrix/telegram#714]
[2021-12-27 16:09:25,296] [ERROR@mau.user.@domain.top] Failed to handle Telegram update
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 250, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 310, in _update
    await self.update_message(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 614, in update_message
    return await portal.handle_telegram_message(self, sender, update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2692, in handle_telegram_message
    event_id = await handler(source, intent, evt, relates_to)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2166, in _handle_telegram_document
    file = await util.transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 238, in transfer_file_to_matrix
    return await _unlocked_transfer_file_to_matrix(
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/file_transfer.py", line 308, in _unlocked_transfer_file_to_matrix
    content_uri = await intent.upload_media(file, upload_mime_type)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 131, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/modules/media_repository.py", line 73, in upload_media
    resp = await self.api.request(
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 362, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in _send
    raise make_request_error(
mautrix.errors.request.MatrixUnknownRequestError: 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by tulir** [comment]
That means the reverse proxy is misconfigured (too small request body size limit)
