### ISSUE TITLE
see errors

### ISSUE THREAD

**Issue by pilikan33** [mautrix/telegram#715]
[2021-12-27 16:08:01,686] [ERROR@mau.user.@domain.top] Failed to handle Telegram update
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 250, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 310, in _update
    await self.update_message(update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/abstract_user.py", line 610, in update_message
    return await portal.handle_telegram_action(self, sender, update)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 2773, in handle_telegram_action
    await self._add_telegram_user(TelegramID(user_id), source)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 957, in _add_telegram_user
    entity: User = await source.client.get_entity(PeerUser(user_id))
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 292, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 466, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=5039929743) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

**Comment by JFingerle** [comment]
I'm getting the same error frequently with version 0.11.3 of the bridge and synapse 1.57.1.

@tulir Is there any workaround or fix for this?
