### ISSUE TITLE
"Authorization error" and "Failed to run post-login sync"

### ISSUE THREAD

**Issue by qsodev** [mautrix/telegram#723]
I just setup mautrix-telegram (v0.11.0) bridge with postgres within docker-compose.
The bridge starts and i can contact the bot and login to Telegram.

But after this I see in the logs:

```
mautrix-telegram    | [2021-12-30 13:13:32,845] [ERROR@mau.user.@<REDACTED>] Authorization error in start(): <class 'telethon.errors.rpcerrorlist.AuthKeyUnregisteredError'>: The key is not registered in the system (caused by GetStateRequest)

...
...

mautrix-telegram    | [2021-12-30 13:13:46,347] [DEBUG@mau.user.@<REDACTED>] Updating contacts of @<REDACTED>...
db_1                | 2021-12-30 13:13:46.354 UTC [29] ERROR:  insert or update on table "contact" violates foreign key constraint "contact_contact_fkey"
db_1                | 2021-12-30 13:13:46.354 UTC [29] DETAIL:  Key (contact)=(<REDACTED>) is not present in table "puppet".
db_1                | 2021-12-30 13:13:46.354 UTC [29] STATEMENT:  COPY "contact"("user", "contact") FROM STDIN (FORMAT binary)
mautrix-telegram    | [2021-12-30 13:13:46,357] [ERROR@mau.user.@<REDACTED>] Failed to run post-login sync
mautrix-telegram    | Traceback (most recent call last):
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 302, in post_login
mautrix-telegram    |     await self.sync_contacts()
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix_telegram/user.py", line 658, in sync_contacts
mautrix-telegram    |     await self.set_contacts(user.id for user in response.users)
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/mautrix_telegram/db/user.py", line 108, in set_contacts
mautrix-telegram    |     await conn.copy_records_to_table("contact", records=records, columns=columns)
mautrix-telegram    |   File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 984, in copy_records_to_table
mautrix-telegram    |     return await self._protocol.copy_in(
mautrix-telegram    |   File "asyncpg/protocol/protocol.pyx", line 529, in copy_in
mautrix-telegram    | asyncpg.exceptions.ForeignKeyViolationError: insert or update on table "contact" violates foreign key constraint "contact_contact_fkey"
mautrix-telegram    | DETAIL:  Key (contact)=(<REDACTED>) is not present in table "puppet".


```
Do you have an idea what went wrong? How can i fix this?

**Comment by tulir** [comment]
The first error shouldn't be logged (it's not a problem), the second one was fixed already
