### ISSUE TITLE
Main loop crashing on v0.11.0

### ISSUE THREAD

**Issue by zotanmew** [mautrix/telegram#726]
Since updating to v0.11.0 the main loop seems to be crashing on every restart. Error log:

```
systemd[1]: Started Matrix-Telegram hybrid puppeting/relaybot bridge.
python[814602]: [2021-12-31 17:04:51,409] [INFO@mau.init] Initializing mautrix-telegram 0.11.0+dev.unknown
python[814602]: [2021-12-31 17:04:51,413] [INFO@mau.init] Initialization complete in 0.11 seconds
python[814602]: [2021-12-31 17:04:51,413] [DEBUG@mau.init] Running startup actions...
python[814602]: [2021-12-31 17:04:51,413] [DEBUG@mau.init] Starting database...
python[814602]: [2021-12-31 17:04:51,413] [DEBUG@mau.db] Connecting to sqlite:///mautrix-telegram.db
python[814602]: [2021-12-31 17:04:51,417] [DEBUG@mau.init] Starting appservice...
python[814602]: [2021-12-31 17:04:51,417] [DEBUG@mau.as] Starting appservice web server on 127.0.0.1:29317
python[814602]: [2021-12-31 17:04:51,417] [INFO@mau.mx] Ensuring connectivity to homeserver
python[814602]: [2021-12-31 17:04:51,430] [DEBUG@mau.mx] Initializing appservice bot
python[814602]: [2021-12-31 17:04:51,432] [DEBUG@mau.user.bot] Initializing client for bot
python[814602]: [2021-12-31 17:04:51,434] [CRITICAL@mau.init] Unexpected error in main event loop
python[814602]: Traceback (most recent call last):
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix/util/program.py", line 216, in _run
python[814602]:     self.loop.run_until_complete(self.start())
python[814602]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
python[814602]:     return future.result()
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 196, in start
python[814602]:     await super().start()
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix/util/program.py", line 243, in start
python[814602]:     await asyncio.gather(*(self.startup_actions or []))
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/bot.py", line 103, in start
python[814602]:     await super().start(delete_unless_authenticated)
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/abstract_user.py", line 275, in start
python[814602]:     await self._init_client()
python[814602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/abstract_user.py", line 205, in _init_client
python[814602]:     self.client = MautrixTelegramClient(
python[814602]:   File "/usr/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 417, in __init__
python[814602]:     self._state_cache = StateCache(
python[814602]:   File "/usr/lib/python3.10/site-packages/telethon/statecache.py", line 39, in __init__
python[814602]:     self._pts_date = initial.pts, initial.date
python[814602]: AttributeError: 'coroutine' object has no attribute 'pts'
```

**Comment by tulir** [comment]
That looks like you didn't install the correct telethon version

**Comment by zotanmew** [comment]
I'm running telethon 1.24.0, which is the latest version as far as I can tell

**Comment by tulir** [comment]
The correct dependencies are specified requirements.txt

**Comment by zotanmew** [comment]
Installing python-telethon-tulir-git (AUR) instead of python-telethon fixed the problem, thank you
