### ISSUE TITLE
Postgres Name does not resolve

### ISSUE THREAD

**Issue by psychopathio** [mautrix/telegram#727]
Telegram & WhatsApp bridges were previously installed on my matrix services without an issue, but recently I decided to rebuild everything from scratch & for some reason the telegram bridge won’t connect to my Postgres database

The bridge will works fine if I used SQLite but not postgress.

docker log:

```
[2022-01-01 02:46:09,790] [[37;1m[41mCRITICAL[0m@[32mmau.init[0m] Unexpected error in main event loop
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 216, in _run
self.loop.run_until_complete(self.start())
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 174, in start
await self.start_db()
File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 163, in start_db
await self.db.start()
File "/usr/lib/python3.9/site-packages/mautrix/util/async_db/asyncpg.py", line 42, in start
self._pool = await asyncpg.create_pool(self.url, **self._db_args)
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 413, in _async__init__
await self._initialize()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 441, in _initialize
await first_ch.connect()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 133, in connect
self._con = await self._pool._get_new_connection()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
con = await connection.connect(
File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 2085, in connect
return await connect_utils._connect(
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
raise last_error
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
return await _connect_addr(
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 776, in _connect_addr
return await __connect_addr(params, timeout, False, *args)
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
tr, pr = await compat.wait_for(connector, timeout=timeout)
File "/usr/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for
return await asyncio.wait_for(fut, timeout)
File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
return fut.result()
File "/usr/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
infos = await self._ensure_resolved(
File "/usr/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
return await loop.getaddrinfo(host, port, family=family, type=type,
File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
return await self.run_in_executor(
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

I apologize if I posted this incorrectly, as this is my first ever issue.

**Comment by JuniorJPDJ** [comment]
thats a problem with networking inside your setup and is not this software issue

**Comment by psychopathio** [comment]
mautrix whatsapp works fine with postgres, why would this be a network issue when the two bridges reside on the same docker using the same postgress user and pass yet one works & the other does not.

**Comment by pidongqianqian** [comment]
i got same error

**Comment by pidongqianqian** [comment]
I found the reason for this error on my server,  this is because an` @ `character appears in the postgres password I set, bridge failed to parse links like this `postgres://username:pas@sword@hostname/dbname`

**Comment by psychopathio** [comment]
> I found the reason for this error on my server, this is because an`@`character appears in the postgres password I set, bridge failed to parse links like this `postgres://username:pas@sword@hostname/dbname`

same here, my pass had an @ character but the strange thing is whatsapp bridge worked without an issue... anyway, thanks for sharing,
