### ISSUE TITLE
Failed to upgrade database: asyncpg.exceptions.NotNullViolationError: column "mx_room" contains null values

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/telegram#731]
Seeing these after upgrading a host

```
[2022-01-05 16:43:16,517] [CRITICAL@mau.db] Failed to upgrade database
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 94, in start
    await self.upgrade_table.upgrade(self)
  File "/usr/lib/python3.9/site-packages/mautrix/util/async_db/upgrade.py", line 124, in upgrade
    await upgrade(conn, db.scheme)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/db/upgrade/v03_reactions.py", line 37, in upgrade_v3
    await conn.execute("ALTER TABLE message ALTER COLUMN mx_room SET NOT NULL")
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 318, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.NotNullViolationError: column "mx_room" contains null values
```

**Comment by tulir** [comment]
🙀
