### ISSUE TITLE
Unable to login: You are already logged in as +None.

### ISSUE THREAD

**Issue by xaionaro** [mautrix/telegram#757]
Something happened to my bridge when I tried to login:
```
Unhandled exception while sending code. Check console for more details.
```
and now it does not allow to login:
```
login
```
```
You are already logged in as +None.
```

And logout:
```
logout
```
```
You're not logged in
```

And the same with QR login:
```
login-qr
```
```
You are already logged in as +None.
```

---

![Screenshot from 2022-02-14 09-41-18](https://user-images.githubusercontent.com/2349376/153839074-ababe46c-a561-4b39-8255-bf543d5cd96e.png)

```
Feb 14 09:39:26 dx-matrix bash[18483]: [2022-02-14 09:39:26,225] [ERROR@mau.commands] Unhandled error while handling command session list from @xaionaro-guest:matrix.dx.center (ref: 1644826048)
Feb 14 09:39:26 dx-matrix bash[18483]: Traceback (most recent call last):
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 474, in handle
Feb 14 09:39:26 dx-matrix bash[18483]:     await self._run_handler(handler, evt)
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/mautrix_telegram/commands/handler.py", line 192, in _run_handler
Feb 14 09:39:26 dx-matrix bash[18483]:     return await handler(evt)
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 323, in __call__
Feb 14 09:39:26 dx-matrix bash[18483]:     return await self._handler(evt)
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/mautrix_telegram/commands/telegram/account.py", line 137, in session
Feb 14 09:39:26 dx-matrix bash[18483]:     res = await evt.sender.client(GetAuthorizationsRequest())
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
Feb 14 09:39:26 dx-matrix bash[18483]:     return await self._call(self._sender, request, ordered=ordered)
Feb 14 09:39:26 dx-matrix bash[18483]:   File "/home/bridges/mautrix-telegram/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call
Feb 14 09:39:26 dx-matrix bash[18483]:     result = await future
Feb 14 09:39:26 dx-matrix bash[18483]: telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetAuthorizationsRequest)
```

**Comment by florisre** [comment]
I am experiencing the same issue. How can I help?

**Comment by tulir** [comment]
Getting logged out should be handled better now
