### ISSUE TITLE
Failed to bridge sticker from matrix to tg ( '>=' not supported between instances of 'int' and 'NoneType')

### ISSUE THREAD

**Issue by Bubu** [mautrix/telegram#768]
Running both mautrix-telegram and mautrix-python @ master.

```
Mar 13 12:13:20 bubu python[16444]: [2022-03-13 12:13:20,236] [DEBUG@mau.mx] Received Matrix event $MNzHvMR46EWmCrRgkmK5fNFsW_sGFW4WkkAkfSX69J0 from @bubu:bubu1.eu in !hLvuDLSwgYUoCjyrwU:bubu1.eu
Mar 13 12:13:20 bubu python[16444]: [2022-03-13 12:13:20,276] [DEBUG@PIL.PngImagePlugin] STREAM b'IHDR' 16 13
Mar 13 12:13:20 bubu python[16444]: [2022-03-13 12:13:20,276] [DEBUG@PIL.PngImagePlugin] STREAM b'IDAT' 41 65536
Mar 13 12:13:20 bubu python[16444]: [2022-03-13 12:13:20,460] [INFO@telethon.39080058.client.uploads] Uploading file of 44674 bytes in 1 chunks of 131072
Mar 13 12:13:20 bubu python[16444]: [2022-03-13 12:13:20,506] [ERROR@mau.portal.626180322] Failed to bridge $MNzHvMR46EWmCrRgkmK5fNFsW_sGFW4WkkAkfSX69J0:v
Mar 13 12:13:20 bubu python[16444]: Traceback (most recent call last):
Mar 13 12:13:20 bubu python[16444]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/portal.py", line 1822, in handle_matrix_message
Mar 13 12:13:20 bubu python[16444]:     await self._handle_matrix_message(sender, content, event_id)
Mar 13 12:13:20 bubu python[16444]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/portal.py", line 1897, in _handle_matrix_message
Mar 13 12:13:20 bubu python[16444]:     await self._handle_matrix_file(
Mar 13 12:13:20 bubu python[16444]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/portal.py", line 1653, in _handle_matrix_file
Mar 13 12:13:20 bubu python[16444]:     force_document = force_document or w * h >= max_image_pixels
Mar 13 12:13:20 bubu python[16444]: TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

**Comment by tulir** [comment]
Did you set `image_as_file_pixels` to null? 🤔

**Comment by Bubu** [comment]
I haven't updated my config in a while...so maybe? let me check.

**Comment by Bubu** [comment]
Yup, adding that field to the config fixes this.

Any chance of having the default value of new config options used as a default in the code when the value isn't set in the config? (config is read-only in my packaging setup)

**Comment by tulir** [comment]
The default value of new config options is used as the default, as long as you don't mess with the `--base-config`/`-b` flag

**Comment by Bubu** [comment]
I see, I think I (but not only me, there's [someone else](https://aur.archlinux.org/cgit/aur.git/tree/mautrix-telegram.service?h=matrix-appservice-telegram#n6) doing the same "mistake") got scared by the permission error you get when using a read-only conf directory, so it was set to the live conf file not the example conf file.

**Comment by tulir** [comment]
The permission errors should happen regardless of the base config flag, `--no-update` is the correct flag for not saving the updated config to disk

**Comment by Bubu** [comment]
Aha, TIL! :-)
