### ISSUE TITLE
Can't communicate with some telegram user

### ISSUE THREAD

**Issue by AlbanBedel** [mautrix/telegram#774]
I'm using double puppeting which is working fine, but one of my telegram contact just doesn't appear in matrix. We already exchanged messages via telegram since setting up the bot, so I tried to manually create the portal with `pm $PHONENUMBER` which gave the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/[intent.py](http://intent.py/)", line 233, in invite_user
    await super().invite_user(room_id, user_id, extra_content=extra_content)
  File "/usr/lib/python3.9/site-packages/mautrix/client/store_[updater.py](http://updater.py/)", line 85, in invite_user
    await super().invite_user(room_id, user_id, extra_content=extra_content)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/[rooms.py](http://rooms.py/)", line 421, in invite_user
    await self.send_member_event(
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/[rooms.py](http://rooms.py/)", line 392, in send_member_event
    content = await self.fill_member_event(room_id, user_id, content) or content
  File "/usr/lib/python3.9/site-packages/mautrix/client/store_[updater.py](http://updater.py/)", line 240, in fill_member_event
    profile = await self.get_profile(user_id)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/user_[data.py](http://data.py/)", line 166, in get_profile
    content = await self.api.request(Method.GET, Path.profile[user_id])
  File "/usr/lib/python3.9/site-packages/mautrix/[api.py](http://api.py/)", line 359, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/[api.py](http://api.py/)", line 256, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: Profile isn't available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/[handler.py](http://handler.py/)", line 474, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/[handler.py](http://handler.py/)", line 192, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/[handler.py](http://handler.py/)", line 323, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/commands/telegram/[misc.py](http://misc.py/)", line 155, in pm
    await portal.create_matrix_room(evt.sender, user, [evt.sender.mxid])
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/[portal.py](http://portal.py/)", line 670, in create_matrix_room
    await self.invite_to_matrix(invites or [])
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/[portal.py](http://portal.py/)", line 584, in invite_to_matrix
    await self.invite_to_matrix(user)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/[portal.py](http://portal.py/)", line 587, in invite_to_matrix
    await self.main_intent.invite_user(
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/[intent.py](http://intent.py/)", line 142, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/[intent.py](http://intent.py/)", line 239, in invite_user
    raise IntentError(f"Failed to invite {user_id} to {room_id}", e)
mautrix.errors.base.IntentError: ('Failed to invite [@MYUSER:MY.DOMAIN](https://matrix.to/#/@MYUSER:MY.DOMAIN) to !SOMEROOMID:[MYDOMAIN](http://DOMAIN/)', MForbidden("Profile isn't available"))
```

In telegram this user has nothing visible in his profile.

**Comment by tulir** [comment]
That probably means you have an outdated bridge and a weird synapse config ("Profile isn't available" doesn't happen with the default config)

**Comment by AlbanBedel** [comment]
The bridge is on v0.11.1  which isn't that old, synapse is on v1.52.0. The synapse config should be fairly standard, any pointer on what I should look for would be appreciated.

**Comment by tulir** [comment]
v0.11.1 is very old, even v0.11.2 is old at this point (but that one should include the relevant error ignoring). The relevant synapse config is probably `limit_profile_requests_to_users_who_share_rooms`
