### ISSUE TITLE
Error while joining via invite link.

### ISSUE THREAD

**Issue by IngwiePhoenix** [mautrix/telegram#778]
Hello!

Quick one: Tried to join the LSPosed Telegram Group via https://t.me/LSPosed and got this:

```
[2022-03-28 11:43:56,435] [ERROR@mau.commands] Unhandled error while handling command join t.me/+1Yve-fJG8W4zMDQ1 from @ingwiephoenix:ingwie.io (ref: 1648467785)
Traceback (most recent call last):
  File "/srv/matrix/telegram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 474, in handle
    await self._run_handler(handler, evt)
  File "/srv/matrix/telegram/lib/python3.7/site-packages/mautrix_telegram/commands/handler.py", line 192, in _run_handler
    return await handler(evt)
  File "/srv/matrix/telegram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 323, in __call__
    return await self._handler(evt)
  File "/srv/matrix/telegram/lib/python3.7/site-packages/mautrix_telegram/commands/telegram/misc.py", line 214, in join
    updates, _ = await _join(evt, identifier, link_type)
  File "/srv/matrix/telegram/lib/python3.7/site-packages/mautrix_telegram/commands/telegram/misc.py", line 171, in _join
    return (await evt.sender.client(ImportChatInviteRequest(identifier))), None
  File "/srv/matrix/telegram/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/srv/matrix/telegram/lib/python3.7/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: INVITE_REQUEST_SENT (caused by ImportChatInviteRequest)
```

Anything I can do to fix this? Thanks!

EDIT: I tried with `t.me/LSPosed` and that worked. But the link shown on the website when you click it, does not work.

**Comment by tulir** [comment]
Like the error message says, it worked fine, so you don't need to do anything to fix it.
