### ISSUE TITLE
Failed to set bot avatar

### ISSUE THREAD

**Issue by Dual-0** [mautrix/telegram#785]
Hello,

FYI: I've installed the bridge today and the default avatar URL is not working correctly. I have used other PNG URLs like `https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Telegram_logo.svg/500px-Telegram_logo.svg.png` but it also didn't work.

mautrix-telegram.log:
```log
[2022-04-17 15:02:34,804] [ERROR@mau.mx] Failed to set bot avatar
Traceback (most recent call last):
  File "/opt/mautrix_bridges/telegram/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 200, in init_as_bot
    await self.az.intent.set_avatar_url(avatar if avatar != "remove" else "")
  File "/opt/mautrix_bridges/telegram/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 123, in wrapper
    return await __method(*args, **kwargs)
  File "/opt/mautrix_bridges/telegram/lib/python3.8/site-packages/mautrix/client/api/user_data.py", line 125, in set_avatar_url
    await self.api.request(
  File "/opt/mautrix_bridges/telegram/lib/python3.8/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/opt/mautrix_bridges/telegram/lib/python3.8/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: This avatar is not allowed
```

**Comment by tulir** [comment]
Only [`mxc://` URLs](https://spec.matrix.org/v1.2/client-server-api/#content-repository) are allowed. The default will work as long as your server has working federation.

**Comment by Dual-0** [comment]
Thanks for this super quick reply. I have checked my config and the following section was wrong configured.

```
    # Permissions for using the bridge.
    # Permitted values:
    #   relaybot - Only use the bridge via the relaybot, no access to commands.
    #       user - Relaybot level + access to commands to create bridges.
    #  puppeting - User level + logging in with a Telegram account.
    #       full - Full access to use the bridge, i.e. previous levels + Matrix login.
    #      admin - Full access to use the bridge and some extra administration commands.
    # Permitted keys:
    #        * - All Matrix users
    #   domain - All users on that homeserver
    #     mxid - Specific user
    permissions:
        "*": "relaybot"
        "public.example.com": "user"
        "example.com": "full"
        "@admin:example.com": "admin"
```

thanks for the hint!
