### ISSUE TITLE
Bridge does not start, PeerIdInvalidError in GetChatsRequest

### ISSUE THREAD

**Issue by 0xC0ncord** [mautrix/telegram#793]
I recently had to create a new Telegram bot user and set up a new API ID and API hash for the bridge I am running because the previous bot was owned by another user who had their account deactivated. I created a new bot, disabled privacy for it, and then created a new application to fill in the API ID and API hash. The bot is failing to start with this traceback:

```
[2022-05-07 00:02:06,197] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 219, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 228, in start
    await super().start()
  File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 253, in start
    await asyncio.gather(*(self.startup_actions or []))
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/bot.py", line 106, in start
    await self.post_login()
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/bot.py", line 117, in post_login
    response = await self.client(GetChatsRequest(chat_ids))
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.PeerIdInvalidError: An invalid Peer was used. Make sure to pass the right peer type and that the value is valid (for instance, bots cannot start conversations) (caused by GetChatsRequest)
```

**Comment by 0xC0ncord** [comment]
I managed to solve this by making a backup of the bridge's sqlite database and then dropping the rows for the chats that the bot is a member of. The old Telegram bot was a member of some private chats that the new Telegram bot didn't have access to, so it seems it was trying to get information about chats that it wasn't a member of.

```
$ cp mautrix-telegram.db mautrix-telegram.db.bak
$ sqlite3 mautrix-telegram.db
> select * from bot_chat; # find all chats/channels
> delete from bot_chat where id = '<old_chat>'; # delete row for old chat/channel
```
