### ISSUE TITLE
mautrix.errors.request.MUnknown: One time key signed_curve25519:AAAAFw already exists

### ISSUE THREAD

**Issue by decentral1se** [mautrix/telegram#794]
Started a one-to-one chat with the bot & the chat was encrypted. Then the logs go into this loop of errors...

```
­2022-05-15T07:35:43.775979000Z [2022-05-15 07:35:43,775] [DEBUG@mau.crypto] Sync response said we have 49 signed curve25519 keys left, sharing new ones...
2022-05-15T07:35:43.779509000Z [2022-05-15 07:35:43,778] [DEBUG@mau.crypto] Going to upload initial account keys
x2022-05-15T07:35:43.780482000Z [2022-05-15 07:35:43,779] [DEBUG@mau.crypto] Uploading 1 one-time keys
2022-05-15T07:35:43.799061000Z [2022-05-15 07:35:43,797] [ERROR@mau.bridge.e2ee.client] Failed to run handler
B2022-05-15T07:35:43.799590000Z Traceback (most recent call last):
~2022-05-15T07:35:43.799857000Z   File "/usr/lib/python3.9/site-packages/mautrix/client/syncer.py", line 229, in _catch_errors
72022-05-15T07:35:43.800136000Z     await handler(data)
2022-05-15T07:35:43.800403000Z   File "/usr/lib/python3.9/site-packages/mautrix/crypto/machine.py", line 113, in handle_otk_count
V2022-05-15T07:35:43.800666000Z     await self.share_keys(otk_count.signed_curve25519)
|2022-05-15T07:35:43.800959000Z   File "/usr/lib/python3.9/site-packages/mautrix/crypto/machine.py", line 204, in share_keys
w2022-05-15T07:35:43.801310000Z     await self.client.upload_keys(one_time_keys=one_time_keys, device_keys=device_keys)
2022-05-15T07:35:43.801588000Z   File "/usr/lib/python3.9/site-packages/mautrix/client/api/modules/crypto.py", line 108, in upload_keys
i2022-05-15T07:35:43.801858000Z     resp = await self.api.request(Method.POST, Path.v3.keys.upload, data)
n2022-05-15T07:35:43.804132000Z   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 383, in request
w2022-05-15T07:35:43.804431000Z     return await self._send(method, full_url, req_content, query_params, headers or {})
l2022-05-15T07:35:43.804709000Z   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 258, in _send
=2022-05-15T07:35:43.805022000Z     raise make_request_error(
&2022-05-15T07:35:43.805302000Z mautrix.errors.request.MUnknown: One time key signed_curve25519:AAAAFw already exists. Old key: {"key":"i0Q/YEK5Sub7F9QnkeOeBGLOoPC3SRAUeplrDcYSPUY","signatures":{"@tbot:matrix.example.com":{"ed25519:KJNRCTKZJP":"aSAXrmlNLeAlZflqmHboxGzglFRok+PbQ25Kq+F6SafcITZuesHylNvBdaDqBMByB0770npUzlYP4CUy/y7bBw"}}}; new key: {'key': '1byKZiVPz03sit/tG5grUYMVZoDwzlRrfF2BkqqUMGI', 'signatures': {'@tbot:matrix.example.com': {'ed25519:KJNRCTKZJP': '+Nl021fhbi9QTlvoZEvI/tGrSF36X/VpZqXOsUI+rWdVF4f8xhNuBaI1HJ89Tuuulk+N6jJAW/I0FvYlXUXCDw'}}}
```

**Comment by decentral1se** [comment]
This problem went away, I don't why! :shrug: :running_woman:
