### ISSUE TITLE
TypeError: 'Obj' object is not callable

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#811]
Latest git/docker version of the bridge (0.11.3+dev.99344c38).

```
mautrix-telegram_1           | 2022-06-28T16:35:21.403991438Z [2022-06-28 16:35:21,401] [ERROR@mau.as] Exception in Matrix event handler
mautrix-telegram_1           | 2022-06-28T16:35:21.404022684Z Traceback (most recent call last):
mautrix-telegram_1           | 2022-06-28T16:35:21.404029880Z   File "/usr/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 239, in try_handle
mautrix-telegram_1           | 2022-06-28T16:35:21.404034243Z     await handler_func(event)
mautrix-telegram_1           | 2022-06-28T16:35:21.404037787Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 936, in int_handle_event
mautrix-telegram_1           | 2022-06-28T16:35:21.404056513Z     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
mautrix-telegram_1           | 2022-06-28T16:35:21.404061513Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 532, in handle_message
mautrix-telegram_1           | 2022-06-28T16:35:21.404066066Z     is_command, text = self.is_command(message)
mautrix-telegram_1           | 2022-06-28T16:35:21.404069709Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 493, in is_command
mautrix-telegram_1           | 2022-06-28T16:35:21.404073339Z     is_command = text.startswith(prefix)
mautrix-telegram_1           | 2022-06-28T16:35:21.404077054Z TypeError: 'Obj' object is not callable
mautrix-telegram_1           | 2022-06-28T16:35:22.734853133Z [2022-06-28 16:35:22,734] [ERROR@mau.as] Exception in Matrix event handler
mautrix-telegram_1           | 2022-06-28T16:35:22.734884398Z Traceback (most recent call last):
mautrix-telegram_1           | 2022-06-28T16:35:22.734890408Z   File "/usr/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 239, in try_handle
mautrix-telegram_1           | 2022-06-28T16:35:22.734894482Z     await handler_func(event)
mautrix-telegram_1           | 2022-06-28T16:35:22.734898347Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 936, in int_handle_event
mautrix-telegram_1           | 2022-06-28T16:35:22.734902167Z     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
mautrix-telegram_1           | 2022-06-28T16:35:22.734906152Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 532, in handle_message
mautrix-telegram_1           | 2022-06-28T16:35:22.734910066Z     is_command, text = self.is_command(message)
mautrix-telegram_1           | 2022-06-28T16:35:22.734913549Z   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 493, in is_command
mautrix-telegram_1           | 2022-06-28T16:35:22.734917153Z     is_command = text.startswith(prefix)
mautrix-telegram_1           | 2022-06-28T16:35:22.734920802Z TypeError: 'Obj' object is not callable
```

**Comment by JuniorJPDJ** [comment]
This seems to be fixed in some of later commits.
