### ISSUE TITLE
[ERROR@mau.commands] Error requesting phone code

### ISSUE THREAD

**Issue by Hagbear** [mautrix/telegram#821]
Hi,

like this bridge very much and work for me very stable since a long time, but now i have a problem, that i do not understood.
I have a user that can not login to telegram.
He was already logged in and to try something he logged out.
After that he can not login again an always gets this error.

`[2022-08-03 12:37:59,821] [ERROR@mau.commands] Error requesting phone code
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_telegram/commands/telegram/auth.py", line 300, in _request_code
    await evt.sender.client.sign_in(phone_number)
  File "/usr/lib/python3.10/site-packages/telethon/client/auth.py", line 338, in sign_in
    me = await self.get_me()
  File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 172, in get_me
    me = (await self(
  File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 88, in _call
    result = await future
telethon.errors.rpcerrorlist.ConnectionNotInitedError: Connection not initialized (caused by GetUsersRequest)`

If i try logon followed by his telefone number from a different matrix account he gets the request and no error appear.

Grettings Marian

**Comment by Hagbear** [comment]
i use the latest docker image

**Comment by martyet** [comment]
Hi, i use the latest docker image too, same issue. After logout command on specific account, i can no longer login via the bridge and same TG account. I did tried to dump selectively rows in databases telethon_sessions and even all relations mentioning my mx username in mx_user_profile - no luck. Problem still occurs :-/

**Comment by averyanalex** [comment]
I can confirm this issue, error also occurs when using login-qr command

**Comment by gragragrab** [comment]
Can confirm, I have the same issue with the latest (as of today) version.

User was successfully logged in.
After logging out, he tries to log in once again.

Here is what I see in logs:

He sends `login` command to the bot, and receives no response.
In the logs:
```logs
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]: [2022-08-31 20:35:50,057] [ERROR@mau.as] Exception in Matrix event handler
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]: Traceback (most recent call last):
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 242, in try_handle
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await handler_func(event)
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 1014, in int_handle_event
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await self.handle_message(evt, was_encrypted=was_encrypted)
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 608, in handle_message
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     sender = await self.bridge.get_user(user_id)
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/__main__.py", line 113, in get_user
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await user.ensure_started()
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/user.py", line 175, in ensure_started
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     return cast(User, await super().ensure_started(even_if_no_session))
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/abstract_user.py", line 305, in ensure_started
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await self.start(delete_unless_authenticated=not even_if_no_session)
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/user.py", line 179, in start
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await super().start()
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/abstract_user.py", line 293, in start
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     await self.client.connect()
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 564, in connect
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     if not await self.is_bot():
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 208, in is_bot
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     self._bot = (await self.get_me()).bot
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 172, in get_me
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     me = (await self(
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     return await self._call(self._sender, request, ordered=ordered)
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 88, in _call
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]:     result = await future
Aug 31 20:35:50 matrix matrix-mautrix-telegram[2602]: telethon.errors.rpcerrorlist.ConnectionNotInitedError: Connection not initialized (caused by GetUsersRequest)
```

After that, he sends `login` command once again. This time, bot sends a link to authorization form. After submiting it, the web gui displays `Internal server error while requesting code.`
In the logs:
```logs
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]: [2022-08-31 20:37:22,827] [ERROR@mau.web.public] Error requesting phone code
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]: Traceback (most recent call last):
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/mautrix_telegram/web/common/auth_api.py", line 124, in post_login_ph>
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:     await user.client.sign_in(phone.strip())
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/auth.py", line 338, in sign_in
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:     me = await self.get_me()
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 172, in get_me
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:     me = (await self(
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:     return await self._call(self._sender, request, ordered=ordered)
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:   File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 88, in _call
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]:     result = await future
Aug 31 20:37:22 matrix matrix-mautrix-telegram[2602]: telethon.errors.rpcerrorlist.ConnectionNotInitedError: Connection not initialized (caused by GetUsersRequest)
```
