### ISSUE TITLE
Failed to run clean-rooms

### ISSUE THREAD

**Issue by pcmid** [mautrix/telegram#852]
I use dendrite polylith as my matrix homeserver. When I run `clean-rooms` it seems failed due to register telegrambot itself.

log
```
[2022-10-16 07:57:43,103] [DEBUG@mau.mx] Received Matrix event $Y7a7e29sY0SWbjFN0dcizJlnYoKa3gWVvMdXhIQX2NQ from @me:homeserver.domain in !ThBcFIDHUFQ:homeserver.domain
[2022-10-16 07:57:43,105] [DEBUG@mau.as.api.bot] req #303: GET https://homeserver.domain/_matrix/client/v3/rooms/%21ThBcFIDHUFQ%3Ahomeserver.domain/joined_members?user_id=@telegrambot:homeserver.domain None
[2022-10-16 07:57:43,152] [DEBUG@mau.as.api.bot] req #303 (/v3/rooms/%21ThBcFIDHUFQ%3Ahomeserver.domain/joined_members) completed in 46.6ms with status 200
[2022-10-16 07:57:43,174] [DEBUG@mau.as.api.bot] req #304: POST https://homeserver.domain/_matrix/client/v3/register?kind=user&user_id=@telegrambot:homeserver.domain {"username": "telegrambot", "type": "m.login.application_service", "inhibit_login": true}
[2022-10-16 07:57:43,217] [DEBUG@mau.as.api.bot] req #304 (/v3/register) completed in 42.9ms with status 500
[2022-10-16 07:57:43,217] [ERROR@mau.commands] Unhandled error while handling command clean-rooms  from @me:homeserver.domain
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_telegram/commands/handler.py", line 192, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py", line 76, in clean_rooms
    results = await _find_rooms(evt.bridge)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py", line 34, in _find_rooms
    rooms = await intent.get_joined_rooms()
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 126, in wrapper
    await __self.ensure_registered()
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 622, in ensure_registered
    await self._register()
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 401, in request
    resp_data, resp = await self._send(
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 256, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: failed to create account: internal API returned "*api.ErrorConflict" error: Conflict: username already exists
[2022-10-16 07:57:43,221] [DEBUG@mau.as.api.bot] req #305: PUT https://homeserver.domain/_matrix/client/v3/rooms/%21ThBcFIDHUFQ%3Ahomeserver.domain/send/m.room.message/mautrix-python_1665907063221458455_134?user_id=@telegrambot:homeserver.domain {"msgtype": "m.notice", "body": "Unhandled error while handling command:\n\n```traceback\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py\", line 491, in handle\n    await self._run_handler(handler, evt)\n  File \"/usr/lib/python3.10/site-packages/mautrix_telegram/commands/handler.py\", line 192, in _run_handler\n    return await handler(evt)\n  File \"/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py\", line 340, in __call__\n    return await self._handler(evt)\n  File \"/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py\", line 76, in clean_rooms\n    results = await _find_rooms(evt.bridge)\n  File \"/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py\", line 34, in _find_rooms\n    rooms = await intent.get_joined_rooms()\n  File \"/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py\", line 126, in wrapper\n    await __self.ensure_registered()\n  File \"/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py\", line 622, in ensure_registered\n    await self._register()\n  File \"/usr/lib/python3.10/site-packages/mautrix/api.py\", line 401, in request\n    resp_data, resp = await self._send(\n  File \"/usr/lib/python3.10/site-packages/mautrix/api.py\", line 256, in _send\n    raise make_request_error(\nmautrix.errors.request.MUnknown: failed to create account: internal API returned \"*api.ErrorConflict\" error: Conflict: username already exists\n```", "format": "org.matrix.custom.html", "formatted_body": "<p>Unhandled error while handling command:</p>\n<pre><code class=\"language-traceback\">Traceback (most recent call last):\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py&quot;, line 491, in handle\n    await self._run_handler(handler, evt)\n  File &quot;/usr/lib/python3.10/site-packages/mautrix_telegram/commands/handler.py&quot;, line 192, in _run_handler\n    return await handler(evt)\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py&quot;, line 340, in __call__\n    return await self._handler(evt)\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py&quot;, line 76, in clean_rooms\n    results = await _find_rooms(evt.bridge)\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py&quot;, line 34, in _find_rooms\n    rooms = await intent.get_joined_rooms()\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py&quot;, line 126, in wrapper\n    await __self.ensure_registered()\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py&quot;, line 622, in ensure_registered\n    await self._register()\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/api.py&quot;, line 401, in request\n    resp_data, resp = await self._send(\n  File &quot;/usr/lib/python3.10/site-packages/mautrix/api.py&quot;, line 256, in _send\n    raise make_request_error(\nmautrix.errors.request.MUnknown: failed to create account: internal API returned &quot;*api.ErrorConflict&quot; error: Conflict: username already exists\n</code></pre>\n"}
```

**Comment by tulir** [comment]
That sounds like a server bug, registering existing accounts shouldn't fail
