### ISSUE TITLE
Dendrite: Error: "...membership from "leave" to "join" as join rule "invite" forbids it"

### ISSUE THREAD

**Issue by IngwiePhoenix** [mautrix/telegram#877]
Hello!

On Dendrite v0.10.7, I get the following error:

```
mautrix-telegram_1  | Traceback (most recent call last):
mautrix-telegram_1  |   File "/usr/lib/python3.10/site-packages/mautrix/client/api/rooms.py", line 335, in join_room
mautrix-telegram_1  |     content = await self.api.request(
mautrix-telegram_1  |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 401, in request
mautrix-telegram_1  |     resp_data, resp = await self._send(
mautrix-telegram_1  |   File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 256, in _send
mautrix-telegram_1  |     raise make_request_error(
mautrix-telegram_1  | mautrix.errors.request.MForbidden: InputRoomEvents auth failed: InputRoomEventsResponse: eventauth: "@tg_1757530373:ingwie.me" is not allowed to change their membership from "leave" to "join" as join rule "invite" forbids it
```

This is the result of using the `pm` command to initiate a chat. All start-up portals were created properly but I had set a limit and wanted to add one more. However, that did not work this time.

Got any idea? Does the bot possibly not have enough permissions?

Thanks and kind regards,
Ingwie

**Comment by comigor** [comment]
Same problem here, and it also happens when I "join" some of the bridged DMs (or even when some people send the first message on DM with me).

I'm using dendrite v0.10.8

**Comment by comigor** [comment]
I'm actually getting a lot of errors on dendrite, so the problem might be there instead of on the bridge (which is strange, given other mautrix bridges work flawlessly):
```
time="2023-01-17T03:57:12.965002504Z" level=warning msg="Roomserver rejected event" error="eventauth: \"@telegram_1011532726:<SERVER_DOMAIN>\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" event_id="$nTc2Y6VUFaTWMxdenQFBvzmWchv9sDeBJTJCkbKcycw" room_id="!nE1Hb0OcpuCYG8Pd:<SERVER_DOMAIN>" type=m.room.member
time="2023-01-17T03:57:12.965132744Z" level=error msg="Failed to join room" error="1 : InputRoomEvents auth failed: InputRoomEventsResponse: eventauth: \"@telegram_1011532726:<SERVER_DOMAIN>\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" room_id="!nE1Hb0OcpuCYG8Pd:<SERVER_DOMAIN>" servers="[]" user_id="@telegram_1011532726:<SERVER_DOMAIN>"
time="2023-01-17T03:57:12.964932824Z" level=warning msg="Stored rejected event" context=missing error="eventauth: \"@telegram_1011532726:<SERVER_DOMAIN>\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" event_id="$nTc2Y6VUFaTWMxdenQFBvzmWchv9sDeBJTJCkbKcycw" kind=KindNew origin="" room_id="!nE1Hb0OcpuCYG8Pd:<SERVER_DOMAIN>" type=m.room.member
time="2023-01-17T03:57:12.959101024Z" level=warning msg="Error authing soft-failed event" context=missing error="eventauth: \"@telegram_1011532726:<SERVER_DOMAIN>\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" event_id="$nTc2Y6VUFaTWMxdenQFBvzmWchv9sDeBJTJCkbKcycw" kind=KindNew origin="" room_id="!nE1Hb0OcpuCYG8Pd:<SERVER_DOMAIN>" type=m.room.member
time="2023-01-17T03:57:12.956869383Z" level=warning msg="Event $nTc2Y6VUFaTWMxdenQFBvzmWchv9sDeBJTJCkbKcycw not allowed by auth events" context=missing error="eventauth: \"@telegram_1011532726:<SERVER_DOMAIN>\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" event_id="$nTc2Y6VUFaTWMxdenQFBvzmWchv9sDeBJTJCkbKcycw" kind=KindNew origin="" room_id="!nE1Hb0OcpuCYG8Pd:<SERVER_DOMAIN>" type=m.room.member
```

**Comment by MaximilianGaedig** [comment]
I had this so much with mautrix-facebok, now I got this on mautrix-telegram aswell, I am using dendrite aswell, might really be an issue with dendrite

**Comment by comigor** [comment]
Yes, since I've commented here, I've migrated my server to [conduit](https://conduit.rs/) and everything I need is working.

**Comment by MaximilianGaedig** [comment]
Yooo conduit is working that well already? That's awesoomeee, I need to switch to it, I had some problems with dendrite anyways

**Comment by marek-rychly** [comment]
Any news on this issue? For me this happens on each invitation of a bot, e.g., mautrix-whatsapp, heisenbridge, etc.

**Comment by tulir** [comment]
Dendrite has bugs with handling room state
