### ISSUE TITLE
PersistentTimestampEmptyError

### ISSUE THREAD

**Issue by KitsuneRal** [mautrix/telegram#881]
After working fine through the holidays and until last night, today the bridge seemed to stop working with the following message recurring in the logs:
```
[2023-01-04 14:01:40,655] [ERROR@telethon.5916592346.client.updates] Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/telethon/client/updates.py", line 320, in _update_loop
    diff = await self(get_diff)
  File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.10/site-packages/telethon/client/users.py", line 88, in _call
    result = await future
telethon.errors.rpcerrorlist.PersistentTimestampEmptyError: Persistent timestamp empty (caused by GetChannelDifferenceRequest)
```
After restarting it, the exceptions are no more but the bridge seems to have stopped working in a few rooms.

**Comment by tulir** [comment]
Worked around in https://github.com/tulir/Telethon/commit/2b247935819661dc511e9f551e714415cf5407c9, although not sure why that happened in the first place
