### ISSUE TITLE
bridge bot does not respond to commands any more

### ISSUE THREAD

**Issue by qsodev** [mautrix/telegram#908]
I recently updated to synapse 1.81 and latest mautrix-telegram bridge.   
Now the bot does no longer respond to commands.

I get this error on startup, it could be the cause for this.

```
[2023-04-13 23:26:55,410] [ERROR@mau.bridge.e2ee.client] Failed to run handler
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/client/syncer.py", line 235, in _catch_errors
    await handler(data)
  File "/usr/lib/python3.10/site-packages/mautrix/crypto/machine.py", line 218, in handle_to_device_event
    await self._receive_forwarded_room_key(decrypted_evt)
  File "/usr/lib/python3.10/site-packages/mautrix/crypto/key_request.py", line 149, in _receive_forwarded_room_key
    await self.crypto_store.put_group_session(
  File "/usr/lib/python3.10/site-packages/mautrix/crypto/store/asyncpg/store.py", line 260, in put_group_session
    int(session.max_age.total_seconds() * 1000),
AttributeError: 'NoneType' object has no attribute 'total_seconds'
```
Any ideas how to fix this?

**Comment by olmari** [comment]
I had same exact issue with Mautrix-signal, fix is already made into mautrix-python in https://github.com/mautrix/python/commit/57a7a5c03697178e5cadc8477a2297840617168b but it still needs to be pushed into bridges themselves.

Immediate fix (per not working room, I think) is to issue `/discardsession`.

**Comment by olmari** [comment]
Just had this same on my Signal bot command room, and issuing `/discardsession` there does NOT solve the issue like it did with DM room with signal contact.. So I suppose "now we wait" for the fix to be deployed to bridges, unless there is some other magic to try for ad-hoc fixing.

**Comment by olmari** [comment]
I tested the mautrix-python fix manually, and that _does_ resolve issue for control channel too, so root cause fix confirmed working, "only" needs deployment.
