### ISSUE TITLE
Matrix -> Telegram reactions not working

### ISSUE THREAD

**Issue by Bubu** [mautrix/telegram#915]
Got the following exceptions whenever trying to send a reaction in matrix. It doesn't appear on the TG side:

```
May 31 08:50:42 bubu python[285]: [2023-05-31 08:50:42,349] [ERROR@mau.as] Exception in Matrix event handler
May 31 08:50:42 bubu python[285]: Traceback (most recent call last):
May 31 08:50:42 bubu python[285]:   File "/usr/lib/python3.11/site-packages/mautrix/appservice/as_handler.py", line 331, in try_handle
May 31 08:50:42 bubu python[285]:     await handler_func(event)
May 31 08:50:42 bubu python[285]:   File "/usr/lib/python3.11/site-packages/mautrix/bridge/matrix.py", line 1074, in int_handle_event
May 31 08:50:42 bubu python[285]:     await self.handle_event(evt)
May 31 08:50:42 bubu python[285]:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/matrix.py", line 415, in handle_event
May 31 08:50:42 bubu python[285]:     await self.handle_reaction(evt)
May 31 08:50:42 bubu python[285]:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/matrix.py", line 288, in handle_reaction
May 31 08:50:42 bubu python[285]:     await portal.handle_matrix_reaction(
May 31 08:50:42 bubu python[285]:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 2468, in handle_matrix_reaction
May 31 08:50:42 bubu python[285]:     or reaction.emoticon not in await user.get_available_reactions()
May 31 08:50:42 bubu python[285]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 08:50:42 bubu python[285]: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Bubu** [comment]
I stared at the logs and the code for a bit now:

I have a bunch of these log lines, but the last one from 26th of May:

> May 26 08:53:01 bubu python[286]: [2023-05-26 08:53:01,819] [DEBUG@mau.user.[@bubu:bubu1.eu](https://matrix.to/#/@bubu:bubu1.eu)] Fetching available emoji reactions

Those all have no corresponsding "Got available emoji reactions though", the last one that has this is from May 21st. 🤔

```
May 21 15:49:13 bubu python[286]: [2023-05-21 15:49:13,142] [DEBUG@mau.user.@bubu:bubu1.eu] Fetching available emoji reactions
May 21 15:49:13 bubu python[286]: [2023-05-21 15:49:13,312] [DEBUG@mau.user.@bubu:bubu1.eu] Got available emoji reactions: {'🤯', '🐳', '💘', '☃', '🫡', '🦄', '🤨', '🤩', '🤷\u200d♀', '🎄', '🙉', ' >
```
Then three fetch attempts within a minute?

```
May 23 10:44:25 bubu python[286]: [2023-05-23 10:44:25,725] [DEBUG@mau.as] Handling transaction 263763 with 1 PDUs
May 23 10:44:25 bubu python[286]: [2023-05-23 10:44:25,725] [DEBUG@mau.as] Finished handling transaction 263763
May 23 10:44:25 bubu python[286]: [2023-05-23 10:44:25,726] [INFO@aiohttp.access] 127.0.0.1 [23/May/2023:08:44:25 +0000] "PUT /_matrix/app/v1/transactions/...>
May 23 10:44:25 bubu python[286]: [2023-05-23 10:44:25,726] [DEBUG@mau.user.@bubu:bubu1.eu] Fetching available emoji reactions
May 23 10:44:27 bubu python[286]: [2023-05-23 10:44:27,879] [DEBUG@mau.as] Handling transaction 263764 with 1 PDUs
May 23 10:44:27 bubu python[286]: [2023-05-23 10:44:27,879] [DEBUG@mau.as] Finished handling transaction 263764
May 23 10:44:27 bubu python[286]: [2023-05-23 10:44:27,880] [INFO@aiohttp.access] 127.0.0.1 [23/May/2023:08:44:27 +0000] "PUT /_matrix/app/v1/transactions/...>
May 23 10:44:27 bubu python[286]: [2023-05-23 10:44:27,880] [DEBUG@mau.user.@bubu:bubu1.eu] Fetching available emoji reactions
May 23 10:45:11 bubu python[286]: [2023-05-23 10:45:11,380] [DEBUG@mau.as] Handling transaction 263765 with 1 PDUs
May 23 10:45:11 bubu python[286]: [2023-05-23 10:45:11,381] [DEBUG@mau.as] Finished handling transaction 263765
May 23 10:45:11 bubu python[286]: [2023-05-23 10:45:11,381] [INFO@aiohttp.access] 127.0.0.1 [23/May/2023:08:45:11 +0000] "PUT /_matrix/app/v1/transactions/...>
May 23 10:45:11 bubu python[286]: [2023-05-23 10:45:11,381] [DEBUG@mau.user.@bubu:bubu1.eu] Fetching available emoji reactions
May 23 10:45:54 bubu python[286]: [2023-05-23 10:45:54,737] [INFO@telethon.39080058.client.updates] Getting difference for account updates (seq: 8325, pts: 493170, qts: 0, date: 2023-05-23 08:45:16+>
```

Then a bunch more of those over the next few days until May 26th, then nothing.

**Comment by Bubu** [comment]
I updated telethon just now to `1.29.0a1` (not sure if related at all), restarted the bridge again, got the following log output and everything works again:
```
Jun 01 08:54:11 bubu python[39242]: [2023-06-01 08:54:11,719] [DEBUG@mau.user.@bubu:bubu1.eu] Fetching available emoji reactions
Jun 01 08:54:11 bubu python[39242]: [2023-06-01 08:54:11,839] [DEBUG@mau.user.@bubu:bubu1.eu] Got available emoji reactions: {'💅', '🤡', '💔', '😨', '🤯', '🔥', '🫡', '😡', '😍', '👨\u200d💻', '🥰'>
```

Feel free to close, if this was just an intermittent outage.
