### ISSUE TITLE
Messages from some Telegram users don't show up on Matrix

### ISSUE THREAD

**Issue by chirayudesai** [mautrix/telegram#924]
I've had multiple matrix.org and telegram rooms bridged using an instance on our own homeserver.

mautrix-telegram version v0.14.1 deployed via matrix-docker-ansible-deploy.

Recently we've noticed some users messages are seen in Telegram, but not Matrix. It's not all of them though.

```
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]: [2023-07-19 20:13:47,810] [ERROR@mau.portal.1294692900] Failed to handle Telegram message 229061 from x via y
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]: Traceback (most recent call last):
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3427, in handle_telegram_message
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     await self._handle_telegram_message(source, sender, evt)
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3536, in _handle_telegram_message
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     await intent.set_typing(self.mxid, timeout=0)
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 414, in set_typing
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     await super().set_typing(room_id, timeout)
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix/client/api/modules/misc.py", line 59, in set_typing
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     await self.api.request(Method.PUT, Path.v3.rooms[room_id].typing[self.mxid], content)
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 395, in request
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     resp_data, resp = await self._send(
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:                       ^^^^^^^^^^^^^^^^^
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 250, in _send
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]:     raise make_request_error(
Jul 19 16:13:47 matrix matrix-mautrix-telegram[607]: mautrix.errors.request.MForbidden: User @telegram_x:domain not in room !room:matrix.org
```

If I try to `/invite @telegram_x:domain` to `!room:matrix.org`, it says user already in room.

**Comment by mikewzr** [comment]
I have the same problem with mautrix-telegram v0.14.2 and dendrite v0.13.3, which is self deployed with docker compose. 

I previously had a setup with matrix-docker-ansible-deploy. The last state of my previous setup used mautrix-telegram v0.13.0 and synapse v1.83.0. I can't remember such kind of problems with my previous setup. But I don't know if the problem source is the newer version of mautrix-telegram or dendrite.

@chirayudesai What matrix server are you using?
