### ISSUE TITLE
bridge claims telegram user not member of portal room

### ISSUE THREAD

**Issue by julianuu** [mautrix/telegram#928]
I am using dendrite.

Messages from a member of a telegram group chat are not bridged to matrix. In the log it says

```
Aug 17 20:17:40: [2023-08-17 20:17:40,257] [ERROR@mau.portal.930743148] Failed to handle Telegram message 129123 from 160718207 via 72808103
Aug 17 20:17:40: Traceback (most recent call last):
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3427, in handle_telegram_message
Aug 17 20:17:40:     await self._handle_telegram_message(source, sender, evt)
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3536, in _handle_telegram_message
Aug 17 20:17:40:     await intent.set_typing(self.mxid, timeout=0)
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 414, in set_typing
Aug 17 20:17:40:     await super().set_typing(room_id, timeout)
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix/client/api/modules/misc.py", line 59, in set_typing
Aug 17 20:17:40:     await self.api.request(Method.PUT, Path.v3.rooms[room_id].typing[self.mxid], content)
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 395, in request
Aug 17 20:17:40:     resp_data, resp = await self._send(
Aug 17 20:17:40:                       ^^^^^^^^^^^^^^^^^
Aug 17 20:17:40:   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 250, in _send
Aug 17 20:17:40:     raise make_request_error(
Aug 17 20:17:40: mautrix.errors.request.MForbidden: user does not belong to room
```

`!tg unbridge` and `!tg delete-portal` fail with similar errors.
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/commands/handler.py", line 192, in _run_handler
    return await handler(evt)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/commands/portal/unbridge.py", line 54, in post_confirm
    await function()
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/portal.py", line 517, in cleanup_and_delete
    await self.cleanup_portal("Portal deleted")
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3886, in cleanup_portal
    await self.cleanup_room(self.main_intent, self.mxid, message, puppets_only)
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/portal.py", line 485, in cleanup_room
    await puppet.default_mxid_intent.leave_room(room_id)
  File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 128, in wrapper
    return await __method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 308, in leave_room
    await super().leave_room(room_id, reason, extra_content, raise_not_in_room)
  File "/usr/lib/python3.11/site-packages/mautrix/client/store_updater.py", line 76, in leave_room
    await super().leave_room(room_id, reason, extra_content, raise_not_in_room)
  File "/usr/lib/python3.11/site-packages/mautrix/client/api/rooms.py", line 495, in leave_room
    await self.api.request(Method.POST, Path.v3.rooms[room_id].leave, content=data)
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 395, in request
    resp_data, resp = await self._send(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 250, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: user "@telegram_(redacted)" is not a member of room "!(redacted)"
```

According to my matrix client and to dendrite's sql database the user "@telegram_…" in question is in fact a member of the portal room.

**Comment by tulir** [comment]
Dendrite is known to be buggy. 0.13.1 may or may not have fixed the bugs, but in general, using Synapse or Conduit is recommended over Dendrite.
