### ISSUE TITLE
"Failed to join room" after restoring from backup

### ISSUE THREAD

**Issue by DomiStyle** [mautrix/telegram#931]
I had to restore the synapse database from backup recently because of some data corruption. The backup was about a day old and everything still seems to be there after the restore.

There is a strange issue with the telegram bridge where a group that was not present at the time the backup was created fails to be created now. I tried rejoining the group in Telegram and in Matrix, and it will tell me that I was invited to the portal but I did not receive anything.
The group is also not listed in the summary from `clean-rooms`.

Here's the exception when mautrix tries to update that group:
```
[2023-10-04 13:57:28,193] [ERROR@mau.user.@domi:example.org] Failed to handle Telegram update
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 596, in ensure_joined
    await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 128, in wrapper
    return await __method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/store_updater.py", line 62, in join_room
    room_id = await super().join_room(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/api/rooms.py", line 335, in join_room
    content = await self.api.request(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 415, in request
    resp_data, resp = await self._send(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 265, in _send
    raise make_request_error(
mautrix.errors.request.MUnknown: Can't join remote room because no servers that are in the room have been provided.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/abstract_user.py", line 283, in _update_catch
    await self._update(update)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/abstract_user.py", line 346, in _update
    await self.update_message(update)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/abstract_user.py", line 721, in update_message
    await task
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/abstract_user.py", line 749, in _call_portal_message_handler
    return await portal.handle_telegram_action(self, sender, update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3691, in handle_telegram_action
    await self._add_telegram_user(sender.id, source)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 1215, in _add_telegram_user
    await puppet.intent_for(self).ensure_joined(self.mxid)
  File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 618, in ensure_joined
    raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix.errors.base.IntentError: Failed to join room !abcd:example.org as @telegram_1234:example.org
```

I tried looking for the room and user mentioned in the exception but neither exists.
Is there a way to synchronize this group again without having to reinstall the telegram bridge?

**Comment by tulir** [comment]
You can delete the relevant rows in the `portal` table

**Comment by DomiStyle** [comment]
In case anyone comes across this, in order to fix this you have to:

1. Clean up the group in the `portal` table (find it via `mxid`)
2. Clean up the profiles in the `mx_user_profile` table (find it via `room_id`) - Take note of the deleted mxids!
3. Clean up the room state in the `mx_room_state` table (find it via `room_id`)
4. The most painful step: Clean up the puppets in the `puppet` table, delete all rows matching the rows deleted in step 2
(You can double check by searching for the id in your Matrix instance that the user does not exist)

I will make sure that I backup all bridges simultaneously with synapse from now on. Would be cool if the bridge had the ability to recreate users if a join fails or an admin command to synchronize users.
