### ISSUE TITLE
login-qr retry issue

### ISSUE THREAD

**Issue by cyberb** [mautrix/telegram#943]
1. Sent login-qr
2. Got QR
3. Tried to take a screenshot and somehow removed QR
4. Sent login-qr again
5. Received the error

Error:
```traceback
Traceback (most recent call last):
  File "/snap/matrix/x11/python/usr/local/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/snap/matrix/x11/python/usr/local/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 192, in _run_handler
    return await handler(evt)
  File "/snap/matrix/x11/python/usr/local/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/snap/matrix/x11/python/usr/local/lib/python3.8/site-packages/mautrix_telegram/commands/telegram/auth.py", line 107, in login_qr
    if await login_as.is_logged_in():
AttributeError: 'NoneType' object has no attribute 'is_logged_in'
```

**Comment by cyberb** [comment]
`logout` is a workaround to start over
