### ISSUE TITLE
Arbitrary as_token does not work

### ISSUE THREAD

**Issue by CTalvio** [mautrix/telegram#954]
I was able to replace the shared auth method and now have this working with mautrix-discord and mautrix-whatsapp.

But with mautrix-telegram, replacing the shared auth token with the appservice token in the format `"as_token:token"` does not seem to work. The quotes disappear in the config after starting the bridge, and double puppeting does not automatically work.

The only relevant entries in the logs seem to be:

```
[2024-01-17 22:49:27,786] [ERROR@mau.user.@casper:domain.fi] Failed to automatically enable custom puppet
Traceback (most recent call last):
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/mautrix_telegram/user.py", line 367, in post_login
    await puppet.switch_mxid(access_token="auto", mxid=self.mxid)
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/mautrix/bridge/custom_puppet.py", line 225, in switch_mxid
    access_token = await self._login_with_shared_secret(mxid)
  File "/opt/mautrix-telegram/lib/python3.10/site-packages/mautrix/bridge/custom_puppet.py", line 209, in _login_with_shared_secret
    raise AutologinError(f"Didn't get an access token: {error_msg}") from None
```

Which to me suggests it's not correctly picking up the appservice token and instead tries to use the old shared secret method to actually log in.

**Comment by winston0410** [comment]
@CTalvio I have encountered this issue as well. Did you escape the quote to make sure it exist, or have you found another solution?

**Comment by CTalvio** [comment]
This was just a case of me using an old version of mautrix-whatsapp without realising.

I thought I had updated it, but asking the bit for the version number revealed I had not.
