### ISSUE TITLE
Unable to communicate with bridge after restart, 404s in log

### ISSUE THREAD

**Issue by koehn** [mautrix/telegram#960]
1. Create bridge running `dock.mau.dev/mautrix/telegram:latest`
2. Chat with telegrambot, login-qr
3. Success! High fives all around
4. Restart bridge (running in Kubernetes, configured to terminate old bridge before starting new instance, never two running simultaneously)
5. Run ping command in telegrambot chat; get no reply
6. Check logs:

```
[2024-04-12 14:47:53,471] [DEBUG@mau.as] Handling transaction 74925 with 1 EDUs
[2024-04-12 14:47:53,474] [DEBUG@mau.as] Finished handling transaction 74925
[2024-04-12 14:47:53,475] [INFO@aiohttp.access] 10.42.165.52 [12/Apr/2024:14:47:53 +0000] "PUT /_matrix/app/v1/transactions/74925 HTTP/1.1" 200 159 "-" "Synapse/1.104.0"
[2024-04-12 14:47:57,044] [DEBUG@mau.as] Handling transaction 74926 with 1 EDUs
[2024-04-12 14:47:57,045] [DEBUG@mau.as] Finished handling transaction 74926
[2024-04-12 14:47:57,046] [INFO@aiohttp.access] 10.42.165.52 [12/Apr/2024:14:47:57 +0000] "PUT /_matrix/app/v1/transactions/74926 HTTP/1.1" 200 159 "-" "Synapse/1.104.0"
[2024-04-12 14:47:57,454] [DEBUG@mau.as] Handling transaction 74927 with 1 PDUs
[2024-04-12 14:47:57,455] [DEBUG@mau.as] Finished handling transaction 74927
[2024-04-12 14:47:57,455] [INFO@aiohttp.access] 10.42.165.52 [12/Apr/2024:14:47:57 +0000] "PUT /_matrix/app/v1/transactions/74927 HTTP/1.1" 200 159 "-" "Synapse/1.104.0"
[2024-04-12 14:47:57,456] [DEBUG@mau.mx] Received Matrix event $WFkDGndQhNqJCiVgGTJAL0lhGuc2YhPkYGEauGBUjlw from @brad:koehn.com in !IoZaJZNMjwNNrLGLfz:koehn.com
[2024-04-12 14:47:57,480] [DEBUG@mau.as.api.bot] req #9: GET https://koehn.com/_matrix/client/v3/rooms/%21IoZaJZNMjwNNrLGLfz%3Akoehn.com/joined_members?user_id=@telegrambot:koehn.com None
[2024-04-12 14:47:57,562] [DEBUG@mau.as.api.bot] req #9 (/v3/rooms/%21IoZaJZNMjwNNrLGLfz%3Akoehn.com/joined_members) completed in 82.3ms with status 200
[2024-04-12 14:47:57,775] [WARNING@telethon.6106432534.network.connection.connection] Server response had invalid buffer: Invalid response buffer (HTTP code 404)
[2024-04-12 14:47:57,777] [ERROR@telethon.6106432534.network.mtprotosender] Server sent invalid buffer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 507, in _recv_loop
    body = await self._connection.recv()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 304, in recv
    raise err
  File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 335, in _recv_loop
    data = await self._recv()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 374, in _recv
    return await self._codec.read_packet(self._reader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/telethon/network/connection/tcpfull.py", line 32, in read_packet
    raise InvalidBufferError(body)
telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)
[2024-04-12 14:47:57,780] [INFO@telethon.6106432534.network.mtprotosender] Closing current connection to begin reconnect...
[2024-04-12 14:47:57,781] [INFO@telethon.6106432534.network.mtprotosender] Connecting to 149.154.167.50:443/TcpFull...
[2024-04-12 14:47:57,956] [INFO@telethon.6106432534.network.mtprotosender] Connection to 149.154.167.50:443/TcpFull complete!
```

Leaving the room and creating a new room results in the same errors in the log. If I wipe the database and start over, it works until the bridge is restarted.

**Comment by koehn** [comment]
Nevermind. Some kind of legacy config error. I generated a new config.yaml and applied my changes to it and now it’s all good.

**Comment by eiabea** [comment]
I am having the same version with verion `v0.15.3`

I tried to re-generate the `config.yaml` file, but no success, after restarting the bridge I get the same result as @koehn

**Comment by eiabea** [comment]
I set the log-level for everything to `DEBUG` and noticed following behavior:

1. restart bot
2. startup logs (without any interaction)
```
mautrix-telegram-1  | [2025-07-27 16:40:03,338] [DEBUG@telethon.91143339.network.mtprotosender] Connection success!
mautrix-telegram-1  | [2025-07-27 16:40:03,339] [DEBUG@telethon.91143339.network.mtprotosender] Starting send loop
mautrix-telegram-1  | [2025-07-27 16:40:03,339] [DEBUG@telethon.91143339.network.mtprotosender] Starting receive loop
mautrix-telegram-1  | [2025-07-27 16:40:03,339] [INFO@telethon.91143339.network.mtprotosender] Connection to 149.154.167.40:443/TcpFull complete!
mautrix-telegram-1  | [2025-07-27 16:40:03,340] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
mautrix-telegram-1  | [2025-07-27 16:40:03,340] [DEBUG@telethon.91143339.network.mtprotosender] Receiving items from the network...
mautrix-telegram-1  | [2025-07-27 16:40:03,367] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531802411495521748 to InvokeWithLayerRequest (7fb174c50c50)
mautrix-telegram-1  | [2025-07-27 16:40:03,367] [DEBUG@telethon.91143339.network.mtprotosender] Encrypting 1 message(s) in 92 bytes for sending
mautrix-telegram-1  | [2025-07-27 16:40:03,367] [DEBUG@telethon.91143339.network.mtprotosender] Encrypted messages put in a queue to be sent
mautrix-telegram-1  | [2025-07-27 16:40:03,367] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
```
3. sending `help` to bot (no response from bot, but also no error in the logs)
```
mautrix-telegram-1  | [2025-07-27 16:41:45,611] [DEBUG@mau.as] Handling transaction 5512 with 1 EDUs
mautrix-telegram-1  | [2025-07-27 16:41:45,611] [DEBUG@mau.as] Finished handling transaction 5512
mautrix-telegram-1  | [2025-07-27 16:41:45,613] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:41:45 +0000] "PUT /_matrix/app/v1/transactions/5512 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:41:46,554] [DEBUG@mau.as] Handling transaction 5513 with 1 EDUs
mautrix-telegram-1  | [2025-07-27 16:41:46,554] [DEBUG@mau.as] Finished handling transaction 5513
mautrix-telegram-1  | [2025-07-27 16:41:46,556] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:41:46 +0000] "PUT /_matrix/app/v1/transactions/5513 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:41:46,695] [DEBUG@mau.as] Handling transaction 5514 with 1 PDUs
mautrix-telegram-1  | [2025-07-27 16:41:46,696] [DEBUG@mau.as] Finished handling transaction 5514
mautrix-telegram-1  | [2025-07-27 16:41:46,697] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:41:46 +0000] "PUT /_matrix/app/v1/transactions/5514 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:41:46,707] [DEBUG@mau.crypto] Ratchet safety info for QGEC5lFViIO8Q3ERFt59ecJ2zxkRtAFYaOJarouvo1g: RatchetSafety(next_index=47, missed_indices=[], lost_indices=[]), ratchet_target_index=47
mautrix-telegram-1  | [2025-07-27 16:41:46,721] [DEBUG@mau.mx] Received Matrix event $EbzvxsPj7mij1neopez-slGgemMBOw7KUkCVr17luVY from @eiabea:matrix.eiabea.com in !whMNxaewOSlJOPXqAZ:matrix.eiabea.com
mautrix-telegram-1  | [2025-07-27 16:41:46,737] [DEBUG@mau.as.api.bot] req #17: GET http://synapse:8008/_matrix/client/v3/rooms/%21whMNxaewOSlJOPXqAZ%3Amatrix.eiabea.com/joined_members?user_id=@telegrambot:matrix.eiabea.com None
mautrix-telegram-1  | [2025-07-27 16:41:46,744] [DEBUG@mau.as.api.bot] req #17 (/v3/rooms/%21whMNxaewOSlJOPXqAZ%3Amatrix.eiabea.com/joined_members) completed in 5.9ms with status 200
mautrix-telegram-1  | [2025-07-27 16:41:46,754] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531802855423639136 to GetStateRequest (7fb174ad5750)
mautrix-telegram-1  | [2025-07-27 16:41:46,754] [DEBUG@telethon.91143339.network.mtprotosender] Encrypting 1 message(s) in 20 bytes for sending
mautrix-telegram-1  | [2025-07-27 16:41:46,754] [DEBUG@telethon.91143339.network.mtprotosender] Encrypted messages put in a queue to be sent
mautrix-telegram-1  | [2025-07-27 16:41:46,754] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
```
4. sending `help` again
```
mautrix-telegram-1  | [2025-07-27 16:42:45,769] [DEBUG@mau.as] Handling transaction 5515 with 1 EDUs
mautrix-telegram-1  | [2025-07-27 16:42:45,770] [DEBUG@mau.as] Finished handling transaction 5515
mautrix-telegram-1  | [2025-07-27 16:42:45,771] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:42:45 +0000] "PUT /_matrix/app/v1/transactions/5515 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:42:46,493] [DEBUG@mau.as] Handling transaction 5516 with 1 EDUs
mautrix-telegram-1  | [2025-07-27 16:42:46,494] [DEBUG@mau.as] Finished handling transaction 5516
mautrix-telegram-1  | [2025-07-27 16:42:46,496] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:42:46 +0000] "PUT /_matrix/app/v1/transactions/5516 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:42:46,654] [DEBUG@mau.as] Handling transaction 5517 with 1 PDUs
mautrix-telegram-1  | [2025-07-27 16:42:46,655] [DEBUG@mau.as] Finished handling transaction 5517
mautrix-telegram-1  | [2025-07-27 16:42:46,656] [INFO@aiohttp.access] 172.22.0.3 [27/Jul/2025:16:42:46 +0000] "PUT /_matrix/app/v1/transactions/5517 HTTP/1.1" 200 159 "-" "Synapse/1.134.0"
mautrix-telegram-1  | [2025-07-27 16:42:46,663] [DEBUG@mau.crypto] Ratchet safety info for QGEC5lFViIO8Q3ERFt59ecJ2zxkRtAFYaOJarouvo1g: RatchetSafety(next_index=48, missed_indices=[], lost_indices=[]), ratchet_target_index=48
mautrix-telegram-1  | [2025-07-27 16:42:46,672] [DEBUG@mau.mx] Received Matrix event $iiRWejChu6nZyMnl3x5pbBYXLorHjldR6cTV0fAzJiw from @eiabea:matrix.eiabea.com in !whMNxaewOSlJOPXqAZ:matrix.eiabea.com
mautrix-telegram-1  | [2025-07-27 16:42:46,675] [DEBUG@mau.as.api.bot] req #20: GET http://synapse:8008/_matrix/client/v3/rooms/%21whMNxaewOSlJOPXqAZ%3Amatrix.eiabea.com/joined_members?user_id=@telegrambot:matrix.eiabea.com None
mautrix-telegram-1  | [2025-07-27 16:42:46,680] [DEBUG@mau.as.api.bot] req #20 (/v3/rooms/%21whMNxaewOSlJOPXqAZ%3Amatrix.eiabea.com/joined_members) completed in 5.2ms with status 200
mautrix-telegram-1  | [2025-07-27 16:42:46,686] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531803112849255060 to GetStateRequest (7fb174ad7750)
mautrix-telegram-1  | [2025-07-27 16:42:46,686] [DEBUG@telethon.91143339.network.mtprotosender] Encrypting 1 message(s) in 20 bytes for sending
mautrix-telegram-1  | [2025-07-27 16:42:46,686] [DEBUG@telethon.91143339.network.mtprotosender] Encrypted messages put in a queue to be sent
mautrix-telegram-1  | [2025-07-27 16:42:46,686] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
mautrix-telegram-1  | [2025-07-27 16:42:46,718] [WARNING@telethon.91143339.network.connection.connection] Server response had invalid buffer: Invalid response buffer (HTTP code 404)
mautrix-telegram-1  | [2025-07-27 16:42:46,718] [ERROR@telethon.91143339.network.mtprotosender] Server sent invalid buffer
mautrix-telegram-1  | Traceback (most recent call last):
mautrix-telegram-1  |   File "/usr/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 507, in _recv_loop
mautrix-telegram-1  |     body = await self._connection.recv()
mautrix-telegram-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mautrix-telegram-1  |   File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 310, in recv
mautrix-telegram-1  |     raise err
mautrix-telegram-1  |   File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 341, in _recv_loop
mautrix-telegram-1  |     data = await self._recv()
mautrix-telegram-1  |            ^^^^^^^^^^^^^^^^^^
mautrix-telegram-1  |   File "/usr/lib/python3.11/site-packages/telethon/network/connection/connection.py", line 380, in _recv
mautrix-telegram-1  |     return await self._codec.read_packet(self._reader)
mautrix-telegram-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mautrix-telegram-1  |   File "/usr/lib/python3.11/site-packages/telethon/network/connection/tcpfull.py", line 32, in read_packet
mautrix-telegram-1  |     raise InvalidBufferError(body)
mautrix-telegram-1  | telethon.errors.common.InvalidBufferError: Invalid response buffer (HTTP code 404)
mautrix-telegram-1  | [2025-07-27 16:42:46,720] [INFO@telethon.91143339.network.mtprotosender] Closing current connection to begin reconnect...
mautrix-telegram-1  | [2025-07-27 16:42:46,721] [INFO@telethon.91143339.network.mtprotosender] Connecting to 149.154.167.40:443/TcpFull...
mautrix-telegram-1  | [2025-07-27 16:42:46,721] [DEBUG@telethon.91143339.network.mtprotosender] Connection attempt 1...
mautrix-telegram-1  | [2025-07-27 16:42:46,750] [DEBUG@telethon.91143339.network.mtprotosender] Connection success!
mautrix-telegram-1  | [2025-07-27 16:42:46,750] [DEBUG@telethon.91143339.network.mtprotosender] Starting send loop
mautrix-telegram-1  | [2025-07-27 16:42:46,750] [DEBUG@telethon.91143339.network.mtprotosender] Starting receive loop
mautrix-telegram-1  | [2025-07-27 16:42:46,751] [INFO@telethon.91143339.network.mtprotosender] Connection to 149.154.167.40:443/TcpFull complete!
mautrix-telegram-1  | [2025-07-27 16:42:46,751] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
mautrix-telegram-1  | [2025-07-27 16:42:46,751] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531803113111993288 to InvokeWithLayerRequest (7fb174c50c50)
mautrix-telegram-1  | [2025-07-27 16:42:46,751] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531803113112800096 to GetStateRequest (7fb174ad5750)
mautrix-telegram-1  | [2025-07-27 16:42:46,752] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531803113113602136 to GetStateRequest (7fb174ad7750)
mautrix-telegram-1  | [2025-07-27 16:42:46,752] [DEBUG@telethon.91143339.network.mtprotosender] Encrypting 3 message(s) in 156 bytes for sending
mautrix-telegram-1  | [2025-07-27 16:42:46,752] [DEBUG@telethon.91143339.network.mtprotosender] Encrypted messages put in a queue to be sent
mautrix-telegram-1  | [2025-07-27 16:42:46,752] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
mautrix-telegram-1  | [2025-07-27 16:42:46,753] [DEBUG@telethon.91143339.network.mtprotosender] Receiving items from the network...
mautrix-telegram-1  | [2025-07-27 16:42:46,753] [DEBUG@telethon.91143339.extensions.messagepacker] Assigned msg_id = 7531803113119238348 to GetUsersRequest (7fb174aeda90)
mautrix-telegram-1  | [2025-07-27 16:42:46,753] [DEBUG@telethon.91143339.network.mtprotosender] Encrypting 1 message(s) in 32 bytes for sending
mautrix-telegram-1  | [2025-07-27 16:42:46,754] [DEBUG@telethon.91143339.network.mtprotosender] Encrypted messages put in a queue to be sent
mautrix-telegram-1  | [2025-07-27 16:42:46,754] [DEBUG@telethon.91143339.network.mtprotosender] Waiting for messages to send...
```
