### ISSUE TITLE
Bridge cannot handle videos (parallel transfer enabled)

### ISSUE THREAD

**Issue by Saiv46** [mautrix/telegram#976]
```
2024-09-24T07:59:55.970081000Z [2024-09-24 07:59:55,969] [ERROR@mau.portal.1711155177] Failed to handle Telegram message 53289 from 1044838901 via 5697932729
2024-09-24T07:59:55.970171000Z Traceback (most recent call last):
2024-09-24T07:59:55.970216000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3426, in handle_telegram_message
2024-09-24T07:59:55.970242000Z     await self._handle_telegram_message(source, sender, evt)
2024-09-24T07:59:55.970272000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 3534, in _handle_telegram_message
2024-09-24T07:59:55.970299000Z     converted = await self._msg_conv.convert(source, intent, is_bot, self.is_channel, evt)
2024-09-24T07:59:55.970324000Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970352000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal_util/message_convert.py", line 175, in convert
2024-09-24T07:59:55.970391000Z     converted = await convert_media(
2024-09-24T07:59:55.970424000Z                 ^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970449000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal_util/message_convert.py", line 626, in _convert_document
2024-09-24T07:59:55.970471000Z     file = await util.transfer_file_to_matrix(
2024-09-24T07:59:55.970495000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970517000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/util/file_transfer.py", line 295, in transfer_file_to_matrix
2024-09-24T07:59:55.970552000Z     return await _unlocked_transfer_file_to_matrix(
2024-09-24T07:59:55.970449000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal_util/message_convert.py", line 626, in _convert_document
2024-09-24T07:59:55.970471000Z     file = await util.transfer_file_to_matrix(
2024-09-24T07:59:55.970495000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970517000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/util/file_transfer.py", line 295, in transfer_file_to_matrix
2024-09-24T07:59:55.970552000Z     return await _unlocked_transfer_file_to_matrix(
2024-09-24T07:59:55.970581000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970608000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/util/file_transfer.py", line 332, in _unlocked_transfer_file_to_matrix
2024-09-24T07:59:55.970633000Z     db_file = await parallel_transfer_to_matrix(
2024-09-24T07:59:55.970662000Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970686000Z   File "/usr/lib/python3.11/site-packages/mautrix_telegram/util/parallel_file_transfer.py", line 342, in parallel_transfer_to_matrix
2024-09-24T07:59:55.970709000Z     content_uri = await intent.upload_media(
2024-09-24T07:59:55.970737000Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.970764000Z   File "/usr/lib/python3.11/site-packages/mautrix/appservice/api/intent.py", line 130, in wrapper
2024-09-24T07:59:55.971012000Z     return await __method(*args, **kwargs)
2024-09-24T07:59:55.971048000Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.971084000Z   File "/usr/lib/python3.11/site-packages/mautrix/client/api/modules/media_repository.py", line 164, in upload_media
2024-09-24T07:59:55.971121000Z     resp = await task
2024-09-24T07:59:55.971149000Z            ^^^^^^^^^^
2024-09-24T07:59:55.971174000Z   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 425, in request
2024-09-24T07:59:55.971194000Z     resp_data, resp = await self._send(
2024-09-24T07:59:55.971215000Z                       ^^^^^^^^^^^^^^^^^
2024-09-24T07:59:55.971240000Z   File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 265, in _send
2024-09-24T07:59:55.971263000Z     raise make_request_error(
2024-09-24T07:59:55.971283000Z mautrix.errors.request.MUnknown: Request must specify a Content-Length

```

**Comment by tulir** [comment]
That looks like the homeserver/media repo can't handle the request rather than a bridge issue. The bridge is being rewritten anyway so there won't be any changes to the old bridge.
