### ISSUE TITLE
Bridging media to Telegram fails due to 403 error on endpoint

### ISSUE THREAD

**Issue by Kimiblock** [mautrix/telegram#978]
This is probably due to some authenticated media thing.

Server: tether.kimiblock.top 

conduwuit 0.4.7rc, legacy media enabled and unfrozen 

Log:

```
Nov 18 14:09:14 python[1260525]: [2024-11-18 14:09:14,138] [ERROR@mau.portal.6541444394<->5358679268] Failed to bridge $i5lFwQlKmJb60OiCLH1eJ-3ccdTEQYFCeDrO83g4huY
Nov 18 14:09:14 python[1260525]: Traceback (most recent call last):
Nov 18 14:09:14 python[1260525]:   File "/usr/lib/python3.12/site-packages/mautrix_telegram/portal.py", line 2190, in handle_matrix_message
Nov 18 14:09:14 python[1260525]:     await self._handle_matrix_message(sender, content, event_id)
Nov 18 14:09:14 python[1260525]:   File "/usr/lib/python3.12/site-packages/mautrix_telegram/portal.py", line 2355, in _handle_matrix_message
Nov 18 14:09:14 python[1260525]:     await self._handle_matrix_file(
Nov 18 14:09:14 python[1260525]:   File "/usr/lib/python3.12/site-packages/mautrix_telegram/portal.py", line 1874, in _handle_matrix_file
Nov 18 14:09:14 python[1260525]:     file = await self.main_intent.download_media(content.url)
Nov 18 14:09:14 python[1260525]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 18 14:09:14 python[1260525]:   File "/usr/lib/python3.12/site-packages/mautrix/client/api/modules/media_repository.py", line 198, in download_media
Nov 18 14:09:14 python[1260525]:     response.raise_for_status()
Nov 18 14:09:14 python[1260525]:   File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
Nov 18 14:09:14 python[1260525]:     raise ClientResponseError(
Nov 18 14:09:14 python[1260525]: aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://tether.kimiblock.top/_matrix/client/v1/media/download/tether.kimiblock.top/kC8Er4cx72LaAEEsvSF5GoTg87uwZx1A?allow_redirect=true'
```

**Comment by Kimiblock** [comment]
> Probably user error or something

@tulir What kind of user error?
