### ISSUE TITLE
Bridge-Telegram

### ISSUE THREAD

**Issue by Laurent333333** [mautrix/telegram#987]
Hello,

I am currently facing an issue with the Telegram bridge: I can no longer send attachments from Element to Telegram.

However, it works fine from Telegram to Element. Here is the error message:

Traceback (most recent call last):
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 2176, in handle_matrix_message
    error=err,
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 2345, in _handle_matrix_message
    body=content.body,
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 1936, in _handle_matrix_file
    client, text=caption.body, html=caption.formatted(Format.HTML)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/mautrix_telegram/tgclient.py", line 77, in send_media
    return self._get_response_message(request, await self(request), entity)
                                               ^^^^^^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/client/users.py", line 67, in _call
    future = sender.send(request, ordered=ordered)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
                ^^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
           ^^^^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/tl/functions/messages.py", line 6002, in _bytes
    if flags & 2:
        ^^^^^^^^^^
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/tl/types/__init__.py", line 12544, in _bytes
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/tl/types/__init__.py", line 11326, in _bytes
  File "/opt/yunohost/mautrix_telegram/lib/python3.11/site-packages/telethon/tl/tlobject.py", line 112, in serialize_bytes
    raise TypeError(
TypeError: bytes or str expected, not <class 'NoneType'>

Could you help me resolve this issue?

Thank you in advance.

**Comment by tulir** [comment]
The call stack doesn't match up with the shown lines, which makes it seem like the installation is corrupted or something

**Comment by Laurent333333** [comment]
Hello,

Thank you for your reply. I have another instance on Docker, and it has not been working for a few days.

I want to clarify that it was working fine before, but it suddenly stopped on both instances. I believe the problem occurred after a Matrix (Synapse) update.

I’ve been searching for the cause of the issue for several days, but I haven’t been able to find it. Here are the logs from the other instance:

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 2190, in handle_matrix_message
    await self._handle_matrix_message(sender, content, event_id)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 2358, in _handle_matrix_message
    await self._handle_matrix_file(
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/portal.py", line 1874, in _handle_matrix_file
    file = await self.main_intent.download_media(content.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/api/modules/media_repository.py", line 189, in download_media
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://matrix.test.com/_matrix/media/v3/download/matrix.test.com/gfiZrsVQbQBZSmpZgdbrmRVe?allow_redirect=true')

Have you noticed the same issue on your end?

PS: Both instances are hosted on separate servers.

Thank you very much for your help.

**Comment by tulir** [comment]
Outdated versions of the bridge won't fully work with updated synapses (the line mismatch in the call stack may be caused by the bridge being updated, but not restarted after updating)

**Comment by Laurent333333** [comment]
It works again, I had to recreate the container with a re-pull of the image.

Thank you very much for your help.
