### ISSUE TITLE
Login-Martix not work

### ISSUE THREAD

**Issue by YosukeKiin** [mautrix/telegram#989]
I have just set up the Telegram Brigde in v 0.15.2.
When I ran the command ‘login-matrix’ and gave my auth token to the bot, I received the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/commands/handler.py", line 194, in _run_handler
    return await handler(evt)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix_telegram/commands/matrix_auth.py", line 78, in enter_matrix_token
    await puppet.switch_mxid(" ".join(evt.args), evt.sender.mxid)
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/custom_puppet.py", line 251, in switch_mxid
    await self.start(check_e2ee_keys=True)
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/custom_puppet.py", line 317, in start
    raise EncryptionKeysFound()
mautrix.bridge.custom_puppet.EncryptionKeysFound: The given access token is for a device that has encryption keys set up. Please provide a fresh token, don't reuse one from another client.

```

I am also logged out of my entire account on all devices a short time, about 10 minutes after logging in via the bridge.

**Comment by tulir** [comment]
User error as per the error message. Follow the docs for double puppeting. https://docs.mau.fi/bridges/general/double-puppeting.html
